// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages an Azure AD/Entra ID connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their Azure AD/Entra ID credentials.
 */
export class AzureOidcConnector extends pulumi.CustomResource {
    /**
     * Get an existing AzureOidcConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AzureOidcConnector {
        return new AzureOidcConnector(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dex:resources:AzureOidcConnector';

    /**
     * Returns true if the given object is an instance of AzureOidcConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AzureOidcConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AzureOidcConnector.__pulumiType;
    }

    /**
     * Azure AD application (client) ID.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * Azure AD application client secret.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * Unique identifier for the Azure connector.
     */
    declare public readonly connectorId: pulumi.Output<string>;
    /**
     * Additional OIDC configuration fields as key-value pairs for advanced scenarios.
     */
    declare public readonly extraOidc: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
     */
    declare public readonly redirectUri: pulumi.Output<string>;
    /**
     * OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
     */
    declare public readonly scopes: pulumi.Output<string[] | undefined>;
    /**
     * Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
     */
    declare public readonly tenantId: pulumi.Output<string>;
    /**
     * Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
     */
    declare public readonly userNameSource: pulumi.Output<string | undefined>;

    /**
     * Create a AzureOidcConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AzureOidcConnectorArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.connectorId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUri'");
            }
            if (args?.tenantId === undefined && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["extraOidc"] = args?.extraOidc;
            resourceInputs["name"] = args?.name;
            resourceInputs["redirectUri"] = args?.redirectUri;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["tenantId"] = args?.tenantId;
            resourceInputs["userNameSource"] = args?.userNameSource;
        } else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["connectorId"] = undefined /*out*/;
            resourceInputs["extraOidc"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["redirectUri"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["tenantId"] = undefined /*out*/;
            resourceInputs["userNameSource"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AzureOidcConnector.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AzureOidcConnector resource.
 */
export interface AzureOidcConnectorArgs {
    /**
     * Azure AD application (client) ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * Azure AD application client secret.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * Unique identifier for the Azure connector.
     */
    connectorId: pulumi.Input<string>;
    /**
     * Additional OIDC configuration fields as key-value pairs for advanced scenarios.
     */
    extraOidc?: pulumi.Input<{[key: string]: any}>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    name: pulumi.Input<string>;
    /**
     * Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
     */
    redirectUri: pulumi.Input<string>;
    /**
     * OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
     */
    tenantId: pulumi.Input<string>;
    /**
     * Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
     */
    userNameSource?: pulumi.Input<string>;
}
