// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages an Azure AD/Entra ID connector in Dex using the Microsoft-specific connector (type: microsoft). This connector provides Microsoft-specific features like group filtering and domain restrictions.
 */
export class AzureMicrosoftConnector extends pulumi.CustomResource {
    /**
     * Get an existing AzureMicrosoftConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AzureMicrosoftConnector {
        return new AzureMicrosoftConnector(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dex:resources:AzureMicrosoftConnector';

    /**
     * Returns true if the given object is an instance of AzureMicrosoftConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AzureMicrosoftConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AzureMicrosoftConnector.__pulumiType;
    }

    /**
     * Azure AD application (client) ID.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * Azure AD application client secret.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * Unique identifier for the Azure Microsoft connector.
     */
    declare public readonly connectorId: pulumi.Output<string>;
    /**
     * Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
     */
    declare public readonly groups: pulumi.Output<string | undefined>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Redirect URI registered in Azure AD. Must match Dex's callback URL.
     */
    declare public readonly redirectUri: pulumi.Output<string>;
    /**
     * Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
     */
    declare public readonly tenant: pulumi.Output<string>;

    /**
     * Create a AzureMicrosoftConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AzureMicrosoftConnectorArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.connectorId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUri'");
            }
            if (args?.tenant === undefined && !opts.urn) {
                throw new Error("Missing required property 'tenant'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["name"] = args?.name;
            resourceInputs["redirectUri"] = args?.redirectUri;
            resourceInputs["tenant"] = args?.tenant;
        } else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["connectorId"] = undefined /*out*/;
            resourceInputs["groups"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["redirectUri"] = undefined /*out*/;
            resourceInputs["tenant"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AzureMicrosoftConnector.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AzureMicrosoftConnector resource.
 */
export interface AzureMicrosoftConnectorArgs {
    /**
     * Azure AD application (client) ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * Azure AD application client secret.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * Unique identifier for the Azure Microsoft connector.
     */
    connectorId: pulumi.Input<string>;
    /**
     * Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
     */
    groups?: pulumi.Input<string>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    name: pulumi.Input<string>;
    /**
     * Redirect URI registered in Azure AD. Must match Dex's callback URL.
     */
    redirectUri: pulumi.Input<string>;
    /**
     * Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
     */
    tenant: pulumi.Input<string>;
}
