// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages an AWS Cognito user pool connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their AWS Cognito credentials.
 */
export class CognitoOidcConnector extends pulumi.CustomResource {
    /**
     * Get an existing CognitoOidcConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CognitoOidcConnector {
        return new CognitoOidcConnector(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dex:resources:CognitoOidcConnector';

    /**
     * Returns true if the given object is an instance of CognitoOidcConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CognitoOidcConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CognitoOidcConnector.__pulumiType;
    }

    /**
     * Cognito app client ID.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * Cognito app client secret.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * Unique identifier for the Cognito connector.
     */
    declare public readonly connectorId: pulumi.Output<string>;
    /**
     * Additional OIDC configuration fields as key-value pairs for advanced scenarios.
     */
    declare public readonly extraOidc: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Redirect URI registered in Cognito. Must match Dex's callback URL.
     */
    declare public readonly redirectUri: pulumi.Output<string>;
    /**
     * AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
     */
    declare public readonly scopes: pulumi.Output<string[] | undefined>;
    /**
     * Source for the username claim. Valid values: 'email' or 'sub' (subject).
     */
    declare public readonly userNameSource: pulumi.Output<string | undefined>;
    /**
     * AWS Cognito user pool ID.
     */
    declare public readonly userPoolId: pulumi.Output<string>;

    /**
     * Create a CognitoOidcConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CognitoOidcConnectorArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.connectorId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUri'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.userPoolId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["extraOidc"] = args?.extraOidc;
            resourceInputs["name"] = args?.name;
            resourceInputs["redirectUri"] = args?.redirectUri;
            resourceInputs["region"] = args?.region;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["userNameSource"] = args?.userNameSource;
            resourceInputs["userPoolId"] = args?.userPoolId;
        } else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["connectorId"] = undefined /*out*/;
            resourceInputs["extraOidc"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["redirectUri"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["userNameSource"] = undefined /*out*/;
            resourceInputs["userPoolId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(CognitoOidcConnector.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CognitoOidcConnector resource.
 */
export interface CognitoOidcConnectorArgs {
    /**
     * Cognito app client ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * Cognito app client secret.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * Unique identifier for the Cognito connector.
     */
    connectorId: pulumi.Input<string>;
    /**
     * Additional OIDC configuration fields as key-value pairs for advanced scenarios.
     */
    extraOidc?: pulumi.Input<{[key: string]: any}>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    name: pulumi.Input<string>;
    /**
     * Redirect URI registered in Cognito. Must match Dex's callback URL.
     */
    redirectUri: pulumi.Input<string>;
    /**
     * AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
     */
    region: pulumi.Input<string>;
    /**
     * OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Source for the username claim. Valid values: 'email' or 'sub' (subject).
     */
    userNameSource?: pulumi.Input<string>;
    /**
     * AWS Cognito user pool ID.
     */
    userPoolId: pulumi.Input<string>;
}
