"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.CognitoOidcConnector = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Manages an AWS Cognito user pool connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their AWS Cognito credentials.
 */
class CognitoOidcConnector extends pulumi.CustomResource {
    /**
     * Get an existing CognitoOidcConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, opts) {
        return new CognitoOidcConnector(name, undefined, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of CognitoOidcConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CognitoOidcConnector.__pulumiType;
    }
    /**
     * Create a CognitoOidcConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name, args, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.connectorId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUri'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.userPoolId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["extraOidc"] = args?.extraOidc;
            resourceInputs["name"] = args?.name;
            resourceInputs["redirectUri"] = args?.redirectUri;
            resourceInputs["region"] = args?.region;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["userNameSource"] = args?.userNameSource;
            resourceInputs["userPoolId"] = args?.userPoolId;
        }
        else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["connectorId"] = undefined /*out*/;
            resourceInputs["extraOidc"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["redirectUri"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["userNameSource"] = undefined /*out*/;
            resourceInputs["userPoolId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(CognitoOidcConnector.__pulumiType, name, resourceInputs, opts);
    }
}
exports.CognitoOidcConnector = CognitoOidcConnector;
/** @internal */
CognitoOidcConnector.__pulumiType = 'dex:resources:CognitoOidcConnector';
//# sourceMappingURL=cognitoOidcConnector.js.map