// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a Google connector in Dex. This connector allows users to authenticate using their Google accounts and supports domain and group-based access control.
 */
export class GoogleConnector extends pulumi.CustomResource {
    /**
     * Get an existing GoogleConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): GoogleConnector {
        return new GoogleConnector(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dex:resources:GoogleConnector';

    /**
     * Returns true if the given object is an instance of GoogleConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GoogleConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GoogleConnector.__pulumiType;
    }

    /**
     * Google OAuth client ID.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * Google OAuth client secret.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * Unique identifier for the Google connector.
     */
    declare public readonly connectorId: pulumi.Output<string>;
    /**
     * Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
     */
    declare public readonly domainToAdminEmail: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * List of Google Groups. Only users in these groups will be allowed to authenticate.
     */
    declare public readonly groups: pulumi.Output<string[] | undefined>;
    /**
     * List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
     */
    declare public readonly hostedDomains: pulumi.Output<string[] | undefined>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
     */
    declare public readonly promptType: pulumi.Output<string | undefined>;
    /**
     * Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
     */
    declare public readonly redirectUri: pulumi.Output<string>;
    /**
     * Path to Google service account JSON file. Required for group-based access control.
     */
    declare public readonly serviceAccountFilePath: pulumi.Output<string | undefined>;

    /**
     * Create a GoogleConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GoogleConnectorArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.connectorId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUri'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["domainToAdminEmail"] = args?.domainToAdminEmail;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["hostedDomains"] = args?.hostedDomains;
            resourceInputs["name"] = args?.name;
            resourceInputs["promptType"] = args?.promptType;
            resourceInputs["redirectUri"] = args?.redirectUri;
            resourceInputs["serviceAccountFilePath"] = args?.serviceAccountFilePath;
        } else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["connectorId"] = undefined /*out*/;
            resourceInputs["domainToAdminEmail"] = undefined /*out*/;
            resourceInputs["groups"] = undefined /*out*/;
            resourceInputs["hostedDomains"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["promptType"] = undefined /*out*/;
            resourceInputs["redirectUri"] = undefined /*out*/;
            resourceInputs["serviceAccountFilePath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GoogleConnector.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a GoogleConnector resource.
 */
export interface GoogleConnectorArgs {
    /**
     * Google OAuth client ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * Google OAuth client secret.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * Unique identifier for the Google connector.
     */
    connectorId: pulumi.Input<string>;
    /**
     * Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
     */
    domainToAdminEmail?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * List of Google Groups. Only users in these groups will be allowed to authenticate.
     */
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
     */
    hostedDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human-readable name for the connector, displayed to users during login.
     */
    name: pulumi.Input<string>;
    /**
     * OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
     */
    promptType?: pulumi.Input<string>;
    /**
     * Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
     */
    redirectUri: pulumi.Input<string>;
    /**
     * Path to Google service account JSON file. Required for group-based access control.
     */
    serviceAccountFilePath?: pulumi.Input<string>;
}
