export type { AzureMicrosoftConnectorArgs } from "./azureMicrosoftConnector";
export type AzureMicrosoftConnector = import("./azureMicrosoftConnector").AzureMicrosoftConnector;
export declare const AzureMicrosoftConnector: typeof import("./azureMicrosoftConnector").AzureMicrosoftConnector;
export type { AzureOidcConnectorArgs } from "./azureOidcConnector";
export type AzureOidcConnector = import("./azureOidcConnector").AzureOidcConnector;
export declare const AzureOidcConnector: typeof import("./azureOidcConnector").AzureOidcConnector;
export type { ClientArgs } from "./client";
export type Client = import("./client").Client;
export declare const Client: typeof import("./client").Client;
export type { CognitoOidcConnectorArgs } from "./cognitoOidcConnector";
export type CognitoOidcConnector = import("./cognitoOidcConnector").CognitoOidcConnector;
export declare const CognitoOidcConnector: typeof import("./cognitoOidcConnector").CognitoOidcConnector;
export type { ConnectorArgs } from "./connector";
export type Connector = import("./connector").Connector;
export declare const Connector: typeof import("./connector").Connector;
export type { GitHubConnectorArgs } from "./gitHubConnector";
export type GitHubConnector = import("./gitHubConnector").GitHubConnector;
export declare const GitHubConnector: typeof import("./gitHubConnector").GitHubConnector;
export type { GitLabConnectorArgs } from "./gitLabConnector";
export type GitLabConnector = import("./gitLabConnector").GitLabConnector;
export declare const GitLabConnector: typeof import("./gitLabConnector").GitLabConnector;
export type { GoogleConnectorArgs } from "./googleConnector";
export type GoogleConnector = import("./googleConnector").GoogleConnector;
export declare const GoogleConnector: typeof import("./googleConnector").GoogleConnector;
export type { LocalConnectorArgs } from "./localConnector";
export type LocalConnector = import("./localConnector").LocalConnector;
export declare const LocalConnector: typeof import("./localConnector").LocalConnector;
