"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocalConnector = exports.GoogleConnector = exports.GitLabConnector = exports.GitHubConnector = exports.Connector = exports.CognitoOidcConnector = exports.Client = exports.AzureOidcConnector = exports.AzureMicrosoftConnector = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.AzureMicrosoftConnector = null;
utilities.lazyLoad(exports, ["AzureMicrosoftConnector"], () => require("./azureMicrosoftConnector"));
exports.AzureOidcConnector = null;
utilities.lazyLoad(exports, ["AzureOidcConnector"], () => require("./azureOidcConnector"));
exports.Client = null;
utilities.lazyLoad(exports, ["Client"], () => require("./client"));
exports.CognitoOidcConnector = null;
utilities.lazyLoad(exports, ["CognitoOidcConnector"], () => require("./cognitoOidcConnector"));
exports.Connector = null;
utilities.lazyLoad(exports, ["Connector"], () => require("./connector"));
exports.GitHubConnector = null;
utilities.lazyLoad(exports, ["GitHubConnector"], () => require("./gitHubConnector"));
exports.GitLabConnector = null;
utilities.lazyLoad(exports, ["GitLabConnector"], () => require("./gitLabConnector"));
exports.GoogleConnector = null;
utilities.lazyLoad(exports, ["GoogleConnector"], () => require("./googleConnector"));
exports.LocalConnector = null;
utilities.lazyLoad(exports, ["LocalConnector"], () => require("./localConnector"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "dex:resources:AzureMicrosoftConnector":
                return new exports.AzureMicrosoftConnector(name, undefined, { urn });
            case "dex:resources:AzureOidcConnector":
                return new exports.AzureOidcConnector(name, undefined, { urn });
            case "dex:resources:Client":
                return new exports.Client(name, undefined, { urn });
            case "dex:resources:CognitoOidcConnector":
                return new exports.CognitoOidcConnector(name, undefined, { urn });
            case "dex:resources:Connector":
                return new exports.Connector(name, undefined, { urn });
            case "dex:resources:GitHubConnector":
                return new exports.GitHubConnector(name, undefined, { urn });
            case "dex:resources:GitLabConnector":
                return new exports.GitLabConnector(name, undefined, { urn });
            case "dex:resources:GoogleConnector":
                return new exports.GoogleConnector(name, undefined, { urn });
            case "dex:resources:LocalConnector":
                return new exports.LocalConnector(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("dex", "resources", _module);
//# sourceMappingURL=index.js.map