# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

caCert: Optional[str]
"""
PEM-encoded CA certificate for validating Dex's TLS certificate.
"""

clientCert: Optional[str]
"""
PEM-encoded client certificate for mTLS to Dex.
"""

clientKey: Optional[str]
"""
PEM-encoded private key for the client certificate.
"""

host: Optional[str]
"""
Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
"""

insecureSkipVerify: Optional[bool]
"""
If true, disables TLS verification (development only).
"""

timeoutSeconds: Optional[int]
"""
Per-RPC timeout in seconds when talking to Dex.
"""

