# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('dex')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def ca_cert(self) -> Optional[str]:
        """
        PEM-encoded CA certificate for validating Dex's TLS certificate.
        """
        return __config__.get('caCert')

    @_builtins.property
    def client_cert(self) -> Optional[str]:
        """
        PEM-encoded client certificate for mTLS to Dex.
        """
        return __config__.get('clientCert')

    @_builtins.property
    def client_key(self) -> Optional[str]:
        """
        PEM-encoded private key for the client certificate.
        """
        return __config__.get('clientKey')

    @_builtins.property
    def host(self) -> Optional[str]:
        """
        Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
        """
        return __config__.get('host')

    @_builtins.property
    def insecure_skip_verify(self) -> Optional[bool]:
        """
        If true, disables TLS verification (development only).
        """
        return __config__.get_bool('insecureSkipVerify')

    @_builtins.property
    def timeout_seconds(self) -> Optional[int]:
        """
        Per-RPC timeout in seconds when talking to Dex.
        """
        return __config__.get_int('timeoutSeconds')

