// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dex

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an Azure AD/Entra ID connector in Dex using the generic OIDC connector (type: oidc).
type AzureOidcConnector struct {
	pulumi.CustomResourceState

	ClientId       pulumi.StringOutput      `pulumi:"clientId"`
	ClientSecret   pulumi.StringOutput      `pulumi:"clientSecret"`
	ConnectorId    pulumi.StringOutput      `pulumi:"connectorId"`
	ExtraOidc      pulumi.MapOutput         `pulumi:"extraOidc"`
	Name           pulumi.StringOutput      `pulumi:"name"`
	RedirectUri    pulumi.StringOutput      `pulumi:"redirectUri"`
	Scopes         pulumi.StringArrayOutput `pulumi:"scopes"`
	TenantId       pulumi.StringOutput      `pulumi:"tenantId"`
	UserNameSource pulumi.StringPtrOutput   `pulumi:"userNameSource"`
}

// NewAzureOidcConnector registers a new resource with the given unique name, arguments, and options.
func NewAzureOidcConnector(ctx *pulumi.Context,
	name string, args *AzureOidcConnectorArgs, opts ...pulumi.ResourceOption) (*AzureOidcConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AzureOidcConnector
	err := ctx.RegisterResource("dex:index:AzureOidcConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureOidcConnector gets an existing AzureOidcConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureOidcConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureOidcConnectorState, opts ...pulumi.ResourceOption) (*AzureOidcConnector, error) {
	var resource AzureOidcConnector
	err := ctx.ReadResource("dex:index:AzureOidcConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureOidcConnector resources.
type azureOidcConnectorState struct {
}

type AzureOidcConnectorState struct {
}

func (AzureOidcConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureOidcConnectorState)(nil)).Elem()
}

type azureOidcConnectorArgs struct {
	ClientId       string                 `pulumi:"clientId"`
	ClientSecret   string                 `pulumi:"clientSecret"`
	ConnectorId    string                 `pulumi:"connectorId"`
	ExtraOidc      map[string]interface{} `pulumi:"extraOidc"`
	Name           string                 `pulumi:"name"`
	RedirectUri    string                 `pulumi:"redirectUri"`
	Scopes         []string               `pulumi:"scopes"`
	TenantId       string                 `pulumi:"tenantId"`
	UserNameSource *string                `pulumi:"userNameSource"`
}

// The set of arguments for constructing a AzureOidcConnector resource.
type AzureOidcConnectorArgs struct {
	ClientId       pulumi.StringInput
	ClientSecret   pulumi.StringInput
	ConnectorId    pulumi.StringInput
	ExtraOidc      pulumi.MapInput
	Name           pulumi.StringInput
	RedirectUri    pulumi.StringInput
	Scopes         pulumi.StringArrayInput
	TenantId       pulumi.StringInput
	UserNameSource pulumi.StringPtrInput
}

func (AzureOidcConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureOidcConnectorArgs)(nil)).Elem()
}

type AzureOidcConnectorInput interface {
	pulumi.Input

	ToAzureOidcConnectorOutput() AzureOidcConnectorOutput
	ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput
}

func (*AzureOidcConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOidcConnector)(nil)).Elem()
}

func (i *AzureOidcConnector) ToAzureOidcConnectorOutput() AzureOidcConnectorOutput {
	return i.ToAzureOidcConnectorOutputWithContext(context.Background())
}

func (i *AzureOidcConnector) ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorOutput)
}

// AzureOidcConnectorArrayInput is an input type that accepts AzureOidcConnectorArray and AzureOidcConnectorArrayOutput values.
// You can construct a concrete instance of `AzureOidcConnectorArrayInput` via:
//
//	AzureOidcConnectorArray{ AzureOidcConnectorArgs{...} }
type AzureOidcConnectorArrayInput interface {
	pulumi.Input

	ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput
	ToAzureOidcConnectorArrayOutputWithContext(context.Context) AzureOidcConnectorArrayOutput
}

type AzureOidcConnectorArray []AzureOidcConnectorInput

func (AzureOidcConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureOidcConnector)(nil)).Elem()
}

func (i AzureOidcConnectorArray) ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput {
	return i.ToAzureOidcConnectorArrayOutputWithContext(context.Background())
}

func (i AzureOidcConnectorArray) ToAzureOidcConnectorArrayOutputWithContext(ctx context.Context) AzureOidcConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorArrayOutput)
}

// AzureOidcConnectorMapInput is an input type that accepts AzureOidcConnectorMap and AzureOidcConnectorMapOutput values.
// You can construct a concrete instance of `AzureOidcConnectorMapInput` via:
//
//	AzureOidcConnectorMap{ "key": AzureOidcConnectorArgs{...} }
type AzureOidcConnectorMapInput interface {
	pulumi.Input

	ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput
	ToAzureOidcConnectorMapOutputWithContext(context.Context) AzureOidcConnectorMapOutput
}

type AzureOidcConnectorMap map[string]AzureOidcConnectorInput

func (AzureOidcConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureOidcConnector)(nil)).Elem()
}

func (i AzureOidcConnectorMap) ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput {
	return i.ToAzureOidcConnectorMapOutputWithContext(context.Background())
}

func (i AzureOidcConnectorMap) ToAzureOidcConnectorMapOutputWithContext(ctx context.Context) AzureOidcConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorMapOutput)
}

type AzureOidcConnectorOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorOutput) ToAzureOidcConnectorOutput() AzureOidcConnectorOutput {
	return o
}

func (o AzureOidcConnectorOutput) ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput {
	return o
}

func (o AzureOidcConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) ExtraOidc() pulumi.MapOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.MapOutput { return v.ExtraOidc }).(pulumi.MapOutput)
}

func (o AzureOidcConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

func (o AzureOidcConnectorOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

func (o AzureOidcConnectorOutput) UserNameSource() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringPtrOutput { return v.UserNameSource }).(pulumi.StringPtrOutput)
}

type AzureOidcConnectorArrayOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorArrayOutput) ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput {
	return o
}

func (o AzureOidcConnectorArrayOutput) ToAzureOidcConnectorArrayOutputWithContext(ctx context.Context) AzureOidcConnectorArrayOutput {
	return o
}

func (o AzureOidcConnectorArrayOutput) Index(i pulumi.IntInput) AzureOidcConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AzureOidcConnector {
		return vs[0].([]*AzureOidcConnector)[vs[1].(int)]
	}).(AzureOidcConnectorOutput)
}

type AzureOidcConnectorMapOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorMapOutput) ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput {
	return o
}

func (o AzureOidcConnectorMapOutput) ToAzureOidcConnectorMapOutputWithContext(ctx context.Context) AzureOidcConnectorMapOutput {
	return o
}

func (o AzureOidcConnectorMapOutput) MapIndex(k pulumi.StringInput) AzureOidcConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AzureOidcConnector {
		return vs[0].(map[string]*AzureOidcConnector)[vs[1].(string)]
	}).(AzureOidcConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorInput)(nil)).Elem(), &AzureOidcConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorArrayInput)(nil)).Elem(), AzureOidcConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorMapInput)(nil)).Elem(), AzureOidcConnectorMap{})
	pulumi.RegisterOutputType(AzureOidcConnectorOutput{})
	pulumi.RegisterOutputType(AzureOidcConnectorArrayOutput{})
	pulumi.RegisterOutputType(AzureOidcConnectorMapOutput{})
}
