// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dex

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an Azure AD/Entra ID connector in Dex using the Microsoft-specific connector (type: microsoft).
type AzureMicrosoftConnector struct {
	pulumi.CustomResourceState

	ClientId     pulumi.StringOutput    `pulumi:"clientId"`
	ClientSecret pulumi.StringOutput    `pulumi:"clientSecret"`
	ConnectorId  pulumi.StringOutput    `pulumi:"connectorId"`
	Groups       pulumi.StringPtrOutput `pulumi:"groups"`
	Name         pulumi.StringOutput    `pulumi:"name"`
	RedirectUri  pulumi.StringOutput    `pulumi:"redirectUri"`
	Tenant       pulumi.StringOutput    `pulumi:"tenant"`
}

// NewAzureMicrosoftConnector registers a new resource with the given unique name, arguments, and options.
func NewAzureMicrosoftConnector(ctx *pulumi.Context,
	name string, args *AzureMicrosoftConnectorArgs, opts ...pulumi.ResourceOption) (*AzureMicrosoftConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.Tenant == nil {
		return nil, errors.New("invalid value for required argument 'Tenant'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AzureMicrosoftConnector
	err := ctx.RegisterResource("dex:index:AzureMicrosoftConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureMicrosoftConnector gets an existing AzureMicrosoftConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureMicrosoftConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureMicrosoftConnectorState, opts ...pulumi.ResourceOption) (*AzureMicrosoftConnector, error) {
	var resource AzureMicrosoftConnector
	err := ctx.ReadResource("dex:index:AzureMicrosoftConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureMicrosoftConnector resources.
type azureMicrosoftConnectorState struct {
}

type AzureMicrosoftConnectorState struct {
}

func (AzureMicrosoftConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureMicrosoftConnectorState)(nil)).Elem()
}

type azureMicrosoftConnectorArgs struct {
	ClientId     string  `pulumi:"clientId"`
	ClientSecret string  `pulumi:"clientSecret"`
	ConnectorId  string  `pulumi:"connectorId"`
	Groups       *string `pulumi:"groups"`
	Name         string  `pulumi:"name"`
	RedirectUri  string  `pulumi:"redirectUri"`
	Tenant       string  `pulumi:"tenant"`
}

// The set of arguments for constructing a AzureMicrosoftConnector resource.
type AzureMicrosoftConnectorArgs struct {
	ClientId     pulumi.StringInput
	ClientSecret pulumi.StringInput
	ConnectorId  pulumi.StringInput
	Groups       pulumi.StringPtrInput
	Name         pulumi.StringInput
	RedirectUri  pulumi.StringInput
	Tenant       pulumi.StringInput
}

func (AzureMicrosoftConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureMicrosoftConnectorArgs)(nil)).Elem()
}

type AzureMicrosoftConnectorInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput
	ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput
}

func (*AzureMicrosoftConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMicrosoftConnector)(nil)).Elem()
}

func (i *AzureMicrosoftConnector) ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput {
	return i.ToAzureMicrosoftConnectorOutputWithContext(context.Background())
}

func (i *AzureMicrosoftConnector) ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorOutput)
}

// AzureMicrosoftConnectorArrayInput is an input type that accepts AzureMicrosoftConnectorArray and AzureMicrosoftConnectorArrayOutput values.
// You can construct a concrete instance of `AzureMicrosoftConnectorArrayInput` via:
//
//	AzureMicrosoftConnectorArray{ AzureMicrosoftConnectorArgs{...} }
type AzureMicrosoftConnectorArrayInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput
	ToAzureMicrosoftConnectorArrayOutputWithContext(context.Context) AzureMicrosoftConnectorArrayOutput
}

type AzureMicrosoftConnectorArray []AzureMicrosoftConnectorInput

func (AzureMicrosoftConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureMicrosoftConnector)(nil)).Elem()
}

func (i AzureMicrosoftConnectorArray) ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput {
	return i.ToAzureMicrosoftConnectorArrayOutputWithContext(context.Background())
}

func (i AzureMicrosoftConnectorArray) ToAzureMicrosoftConnectorArrayOutputWithContext(ctx context.Context) AzureMicrosoftConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorArrayOutput)
}

// AzureMicrosoftConnectorMapInput is an input type that accepts AzureMicrosoftConnectorMap and AzureMicrosoftConnectorMapOutput values.
// You can construct a concrete instance of `AzureMicrosoftConnectorMapInput` via:
//
//	AzureMicrosoftConnectorMap{ "key": AzureMicrosoftConnectorArgs{...} }
type AzureMicrosoftConnectorMapInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput
	ToAzureMicrosoftConnectorMapOutputWithContext(context.Context) AzureMicrosoftConnectorMapOutput
}

type AzureMicrosoftConnectorMap map[string]AzureMicrosoftConnectorInput

func (AzureMicrosoftConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureMicrosoftConnector)(nil)).Elem()
}

func (i AzureMicrosoftConnectorMap) ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput {
	return i.ToAzureMicrosoftConnectorMapOutputWithContext(context.Background())
}

func (i AzureMicrosoftConnectorMap) ToAzureMicrosoftConnectorMapOutputWithContext(ctx context.Context) AzureMicrosoftConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorMapOutput)
}

type AzureMicrosoftConnectorOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorOutput) ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput {
	return o
}

func (o AzureMicrosoftConnectorOutput) ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput {
	return o
}

func (o AzureMicrosoftConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

func (o AzureMicrosoftConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

func (o AzureMicrosoftConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

func (o AzureMicrosoftConnectorOutput) Groups() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringPtrOutput { return v.Groups }).(pulumi.StringPtrOutput)
}

func (o AzureMicrosoftConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o AzureMicrosoftConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

func (o AzureMicrosoftConnectorOutput) Tenant() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.Tenant }).(pulumi.StringOutput)
}

type AzureMicrosoftConnectorArrayOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorArrayOutput) ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput {
	return o
}

func (o AzureMicrosoftConnectorArrayOutput) ToAzureMicrosoftConnectorArrayOutputWithContext(ctx context.Context) AzureMicrosoftConnectorArrayOutput {
	return o
}

func (o AzureMicrosoftConnectorArrayOutput) Index(i pulumi.IntInput) AzureMicrosoftConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AzureMicrosoftConnector {
		return vs[0].([]*AzureMicrosoftConnector)[vs[1].(int)]
	}).(AzureMicrosoftConnectorOutput)
}

type AzureMicrosoftConnectorMapOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorMapOutput) ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput {
	return o
}

func (o AzureMicrosoftConnectorMapOutput) ToAzureMicrosoftConnectorMapOutputWithContext(ctx context.Context) AzureMicrosoftConnectorMapOutput {
	return o
}

func (o AzureMicrosoftConnectorMapOutput) MapIndex(k pulumi.StringInput) AzureMicrosoftConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AzureMicrosoftConnector {
		return vs[0].(map[string]*AzureMicrosoftConnector)[vs[1].(string)]
	}).(AzureMicrosoftConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorInput)(nil)).Elem(), &AzureMicrosoftConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorArrayInput)(nil)).Elem(), AzureMicrosoftConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorMapInput)(nil)).Elem(), AzureMicrosoftConnectorMap{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorOutput{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorArrayOutput{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorMapOutput{})
}
