// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dex

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an AWS Cognito user pool connector in Dex using the generic OIDC connector (type: oidc).
type CognitoOidcConnector struct {
	pulumi.CustomResourceState

	ClientId       pulumi.StringOutput      `pulumi:"clientId"`
	ClientSecret   pulumi.StringOutput      `pulumi:"clientSecret"`
	ConnectorId    pulumi.StringOutput      `pulumi:"connectorId"`
	ExtraOidc      pulumi.MapOutput         `pulumi:"extraOidc"`
	Name           pulumi.StringOutput      `pulumi:"name"`
	RedirectUri    pulumi.StringOutput      `pulumi:"redirectUri"`
	Region         pulumi.StringOutput      `pulumi:"region"`
	Scopes         pulumi.StringArrayOutput `pulumi:"scopes"`
	UserNameSource pulumi.StringPtrOutput   `pulumi:"userNameSource"`
	UserPoolId     pulumi.StringOutput      `pulumi:"userPoolId"`
}

// NewCognitoOidcConnector registers a new resource with the given unique name, arguments, and options.
func NewCognitoOidcConnector(ctx *pulumi.Context,
	name string, args *CognitoOidcConnectorArgs, opts ...pulumi.ResourceOption) (*CognitoOidcConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.UserPoolId == nil {
		return nil, errors.New("invalid value for required argument 'UserPoolId'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CognitoOidcConnector
	err := ctx.RegisterResource("dex:index:CognitoOidcConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCognitoOidcConnector gets an existing CognitoOidcConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCognitoOidcConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CognitoOidcConnectorState, opts ...pulumi.ResourceOption) (*CognitoOidcConnector, error) {
	var resource CognitoOidcConnector
	err := ctx.ReadResource("dex:index:CognitoOidcConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CognitoOidcConnector resources.
type cognitoOidcConnectorState struct {
}

type CognitoOidcConnectorState struct {
}

func (CognitoOidcConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoOidcConnectorState)(nil)).Elem()
}

type cognitoOidcConnectorArgs struct {
	ClientId       string                 `pulumi:"clientId"`
	ClientSecret   string                 `pulumi:"clientSecret"`
	ConnectorId    string                 `pulumi:"connectorId"`
	ExtraOidc      map[string]interface{} `pulumi:"extraOidc"`
	Name           string                 `pulumi:"name"`
	RedirectUri    string                 `pulumi:"redirectUri"`
	Region         string                 `pulumi:"region"`
	Scopes         []string               `pulumi:"scopes"`
	UserNameSource *string                `pulumi:"userNameSource"`
	UserPoolId     string                 `pulumi:"userPoolId"`
}

// The set of arguments for constructing a CognitoOidcConnector resource.
type CognitoOidcConnectorArgs struct {
	ClientId       pulumi.StringInput
	ClientSecret   pulumi.StringInput
	ConnectorId    pulumi.StringInput
	ExtraOidc      pulumi.MapInput
	Name           pulumi.StringInput
	RedirectUri    pulumi.StringInput
	Region         pulumi.StringInput
	Scopes         pulumi.StringArrayInput
	UserNameSource pulumi.StringPtrInput
	UserPoolId     pulumi.StringInput
}

func (CognitoOidcConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoOidcConnectorArgs)(nil)).Elem()
}

type CognitoOidcConnectorInput interface {
	pulumi.Input

	ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput
	ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput
}

func (*CognitoOidcConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoOidcConnector)(nil)).Elem()
}

func (i *CognitoOidcConnector) ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput {
	return i.ToCognitoOidcConnectorOutputWithContext(context.Background())
}

func (i *CognitoOidcConnector) ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorOutput)
}

// CognitoOidcConnectorArrayInput is an input type that accepts CognitoOidcConnectorArray and CognitoOidcConnectorArrayOutput values.
// You can construct a concrete instance of `CognitoOidcConnectorArrayInput` via:
//
//	CognitoOidcConnectorArray{ CognitoOidcConnectorArgs{...} }
type CognitoOidcConnectorArrayInput interface {
	pulumi.Input

	ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput
	ToCognitoOidcConnectorArrayOutputWithContext(context.Context) CognitoOidcConnectorArrayOutput
}

type CognitoOidcConnectorArray []CognitoOidcConnectorInput

func (CognitoOidcConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoOidcConnector)(nil)).Elem()
}

func (i CognitoOidcConnectorArray) ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput {
	return i.ToCognitoOidcConnectorArrayOutputWithContext(context.Background())
}

func (i CognitoOidcConnectorArray) ToCognitoOidcConnectorArrayOutputWithContext(ctx context.Context) CognitoOidcConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorArrayOutput)
}

// CognitoOidcConnectorMapInput is an input type that accepts CognitoOidcConnectorMap and CognitoOidcConnectorMapOutput values.
// You can construct a concrete instance of `CognitoOidcConnectorMapInput` via:
//
//	CognitoOidcConnectorMap{ "key": CognitoOidcConnectorArgs{...} }
type CognitoOidcConnectorMapInput interface {
	pulumi.Input

	ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput
	ToCognitoOidcConnectorMapOutputWithContext(context.Context) CognitoOidcConnectorMapOutput
}

type CognitoOidcConnectorMap map[string]CognitoOidcConnectorInput

func (CognitoOidcConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoOidcConnector)(nil)).Elem()
}

func (i CognitoOidcConnectorMap) ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput {
	return i.ToCognitoOidcConnectorMapOutputWithContext(context.Background())
}

func (i CognitoOidcConnectorMap) ToCognitoOidcConnectorMapOutputWithContext(ctx context.Context) CognitoOidcConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorMapOutput)
}

type CognitoOidcConnectorOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorOutput) ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput {
	return o
}

func (o CognitoOidcConnectorOutput) ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput {
	return o
}

func (o CognitoOidcConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) ExtraOidc() pulumi.MapOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.MapOutput { return v.ExtraOidc }).(pulumi.MapOutput)
}

func (o CognitoOidcConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o CognitoOidcConnectorOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

func (o CognitoOidcConnectorOutput) UserNameSource() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringPtrOutput { return v.UserNameSource }).(pulumi.StringPtrOutput)
}

func (o CognitoOidcConnectorOutput) UserPoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.UserPoolId }).(pulumi.StringOutput)
}

type CognitoOidcConnectorArrayOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorArrayOutput) ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput {
	return o
}

func (o CognitoOidcConnectorArrayOutput) ToCognitoOidcConnectorArrayOutputWithContext(ctx context.Context) CognitoOidcConnectorArrayOutput {
	return o
}

func (o CognitoOidcConnectorArrayOutput) Index(i pulumi.IntInput) CognitoOidcConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CognitoOidcConnector {
		return vs[0].([]*CognitoOidcConnector)[vs[1].(int)]
	}).(CognitoOidcConnectorOutput)
}

type CognitoOidcConnectorMapOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorMapOutput) ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput {
	return o
}

func (o CognitoOidcConnectorMapOutput) ToCognitoOidcConnectorMapOutputWithContext(ctx context.Context) CognitoOidcConnectorMapOutput {
	return o
}

func (o CognitoOidcConnectorMapOutput) MapIndex(k pulumi.StringInput) CognitoOidcConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CognitoOidcConnector {
		return vs[0].(map[string]*CognitoOidcConnector)[vs[1].(string)]
	}).(CognitoOidcConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorInput)(nil)).Elem(), &CognitoOidcConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorArrayInput)(nil)).Elem(), CognitoOidcConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorMapInput)(nil)).Elem(), CognitoOidcConnectorMap{})
	pulumi.RegisterOutputType(CognitoOidcConnectorOutput{})
	pulumi.RegisterOutputType(CognitoOidcConnectorArrayOutput{})
	pulumi.RegisterOutputType(CognitoOidcConnectorMapOutput{})
}
