// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dex

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// PEM-encoded CA certificate for validating Dex's TLS certificate.
	CaCert pulumi.StringPtrOutput `pulumi:"caCert"`
	// PEM-encoded client certificate for mTLS to Dex.
	ClientCert pulumi.StringPtrOutput `pulumi:"clientCert"`
	// PEM-encoded private key for the client certificate.
	ClientKey pulumi.StringPtrOutput `pulumi:"clientKey"`
	// Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
	Host pulumi.StringOutput `pulumi:"host"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Host == nil {
		return nil, errors.New("invalid value for required argument 'Host'")
	}
	if args.CaCert != nil {
		args.CaCert = pulumi.ToSecret(args.CaCert).(pulumi.StringPtrInput)
	}
	if args.ClientCert != nil {
		args.ClientCert = pulumi.ToSecret(args.ClientCert).(pulumi.StringPtrInput)
	}
	if args.ClientKey != nil {
		args.ClientKey = pulumi.ToSecret(args.ClientKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"caCert",
		"clientCert",
		"clientKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:dex", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// PEM-encoded CA certificate for validating Dex's TLS certificate.
	CaCert *string `pulumi:"caCert"`
	// PEM-encoded client certificate for mTLS to Dex.
	ClientCert *string `pulumi:"clientCert"`
	// PEM-encoded private key for the client certificate.
	ClientKey *string `pulumi:"clientKey"`
	// Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
	Host string `pulumi:"host"`
	// If true, disables TLS verification (development only).
	InsecureSkipVerify *bool `pulumi:"insecureSkipVerify"`
	// Per-RPC timeout in seconds when talking to Dex.
	TimeoutSeconds *int `pulumi:"timeoutSeconds"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// PEM-encoded CA certificate for validating Dex's TLS certificate.
	CaCert pulumi.StringPtrInput
	// PEM-encoded client certificate for mTLS to Dex.
	ClientCert pulumi.StringPtrInput
	// PEM-encoded private key for the client certificate.
	ClientKey pulumi.StringPtrInput
	// Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
	Host pulumi.StringInput
	// If true, disables TLS verification (development only).
	InsecureSkipVerify pulumi.BoolPtrInput
	// Per-RPC timeout in seconds when talking to Dex.
	TimeoutSeconds pulumi.IntPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// PEM-encoded CA certificate for validating Dex's TLS certificate.
func (o ProviderOutput) CaCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.CaCert }).(pulumi.StringPtrOutput)
}

// PEM-encoded client certificate for mTLS to Dex.
func (o ProviderOutput) ClientCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientCert }).(pulumi.StringPtrOutput)
}

// PEM-encoded private key for the client certificate.
func (o ProviderOutput) ClientKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientKey }).(pulumi.StringPtrOutput)
}

// Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
func (o ProviderOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Host }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
