// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    export interface GitHubOrgArgs {
        /**
         * GitHub organization name.
         */
        name: pulumi.Input<string>;
        /**
         * List of team names within the organization. If empty, all members of the organization can authenticate.
         */
        teams?: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface OIDCClaimMappingArgs {
        /**
         * The OIDC claim key that contains the user's email address.
         */
        emailKey?: pulumi.Input<string>;
        /**
         * The OIDC claim key that contains the user's group memberships.
         */
        groupsKey?: pulumi.Input<string>;
    }

    export interface OIDCConfigArgs {
        /**
         * Mapping of OIDC claims to Dex user attributes.
         */
        claimMapping?: pulumi.Input<inputs.resources.OIDCClaimMappingArgs>;
        /**
         * The OIDC client ID.
         */
        clientId: pulumi.Input<string>;
        /**
         * The OIDC client secret.
         */
        clientSecret: pulumi.Input<string>;
        /**
         * Additional OIDC configuration fields as key-value pairs.
         */
        extra?: pulumi.Input<{[key: string]: any}>;
        /**
         * If true, skip verification of the issuer URL. Not recommended for production.
         */
        insecureIssuer?: pulumi.Input<boolean>;
        /**
         * If true, skip verification of the 'email_verified' claim. Not recommended for production.
         */
        insecureSkipEmailVerified?: pulumi.Input<boolean>;
        /**
         * The OIDC issuer URL (e.g., 'https://accounts.google.com').
         */
        issuer: pulumi.Input<string>;
        /**
         * The redirect URI registered with the OIDC provider. Must match Dex's callback URL.
         */
        redirectUri: pulumi.Input<string>;
        /**
         * List of OIDC scopes to request (e.g., 'openid', 'profile', 'email'). Defaults to ['openid', 'profile', 'email'] if not specified.
         */
        scopes?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * The claim key to use as the username (e.g., 'preferred_username', 'email', 'sub').
         */
        userNameKey?: pulumi.Input<string>;
    }
}
