// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface OIDCClaimMappingArgs {
    emailKey?: pulumi.Input<string>;
    groupsKey?: pulumi.Input<string>;
}

export interface OIDCConfigArgs {
    claimMapping?: pulumi.Input<inputs.OIDCClaimMappingArgs>;
    clientId: pulumi.Input<string>;
    clientSecret: pulumi.Input<string>;
    extra?: pulumi.Input<{[key: string]: any}>;
    insecureIssuer?: pulumi.Input<boolean>;
    insecureSkipEmailVerified?: pulumi.Input<boolean>;
    issuer: pulumi.Input<string>;
    redirectUri: pulumi.Input<string>;
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    userNameKey?: pulumi.Input<string>;
}
