// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    export interface GitHubOrg {
        /**
         * GitHub organization name.
         */
        name: string;
        /**
         * List of team names within the organization. If empty, all members of the organization can authenticate.
         */
        teams?: string[];
    }

    export interface OIDCClaimMapping {
        /**
         * The OIDC claim key that contains the user's email address.
         */
        emailKey?: string;
        /**
         * The OIDC claim key that contains the user's group memberships.
         */
        groupsKey?: string;
    }

    export interface OIDCConfig {
        /**
         * Mapping of OIDC claims to Dex user attributes.
         */
        claimMapping?: outputs.resources.OIDCClaimMapping;
        /**
         * The OIDC client ID.
         */
        clientId: string;
        /**
         * The OIDC client secret.
         */
        clientSecret: string;
        /**
         * Additional OIDC configuration fields as key-value pairs.
         */
        extra?: {[key: string]: any};
        /**
         * If true, skip verification of the issuer URL. Not recommended for production.
         */
        insecureIssuer?: boolean;
        /**
         * If true, skip verification of the 'email_verified' claim. Not recommended for production.
         */
        insecureSkipEmailVerified?: boolean;
        /**
         * The OIDC issuer URL (e.g., 'https://accounts.google.com').
         */
        issuer: string;
        /**
         * The redirect URI registered with the OIDC provider. Must match Dex's callback URL.
         */
        redirectUri: string;
        /**
         * List of OIDC scopes to request (e.g., 'openid', 'profile', 'email'). Defaults to ['openid', 'profile', 'email'] if not specified.
         */
        scopes?: string[];
        /**
         * The claim key to use as the username (e.g., 'preferred_username', 'email', 'sub').
         */
        userNameKey?: string;
    }

}
