// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface OIDCClaimMapping {
    emailKey?: string;
    groupsKey?: string;
}

export interface OIDCConfig {
    claimMapping?: outputs.OIDCClaimMapping;
    clientId: string;
    clientSecret: string;
    extra?: {[key: string]: any};
    insecureIssuer?: boolean;
    insecureSkipEmailVerified?: boolean;
    issuer: string;
    redirectUri: string;
    scopes?: string[];
    userNameKey?: string;
}

