// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an Azure AD/Entra ID connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their Azure AD/Entra ID credentials.
type AzureOidcConnector struct {
	pulumi.CustomResourceState

	// Azure AD application (client) ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Azure AD application client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the Azure connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc pulumi.MapOutput `pulumi:"extraOidc"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
	Scopes pulumi.StringArrayOutput `pulumi:"scopes"`
	// Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
	// Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
	UserNameSource pulumi.StringPtrOutput `pulumi:"userNameSource"`
}

// NewAzureOidcConnector registers a new resource with the given unique name, arguments, and options.
func NewAzureOidcConnector(ctx *pulumi.Context,
	name string, args *AzureOidcConnectorArgs, opts ...pulumi.ResourceOption) (*AzureOidcConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AzureOidcConnector
	err := ctx.RegisterResource("dex:resources:AzureOidcConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureOidcConnector gets an existing AzureOidcConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureOidcConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureOidcConnectorState, opts ...pulumi.ResourceOption) (*AzureOidcConnector, error) {
	var resource AzureOidcConnector
	err := ctx.ReadResource("dex:resources:AzureOidcConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureOidcConnector resources.
type azureOidcConnectorState struct {
}

type AzureOidcConnectorState struct {
}

func (AzureOidcConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureOidcConnectorState)(nil)).Elem()
}

type azureOidcConnectorArgs struct {
	// Azure AD application (client) ID.
	ClientId string `pulumi:"clientId"`
	// Azure AD application client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the Azure connector.
	ConnectorId string `pulumi:"connectorId"`
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc map[string]interface{} `pulumi:"extraOidc"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
	RedirectUri string `pulumi:"redirectUri"`
	// OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
	Scopes []string `pulumi:"scopes"`
	// Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
	TenantId string `pulumi:"tenantId"`
	// Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
	UserNameSource *string `pulumi:"userNameSource"`
}

// The set of arguments for constructing a AzureOidcConnector resource.
type AzureOidcConnectorArgs struct {
	// Azure AD application (client) ID.
	ClientId pulumi.StringInput
	// Azure AD application client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the Azure connector.
	ConnectorId pulumi.StringInput
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc pulumi.MapInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
	RedirectUri pulumi.StringInput
	// OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
	Scopes pulumi.StringArrayInput
	// Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
	TenantId pulumi.StringInput
	// Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
	UserNameSource pulumi.StringPtrInput
}

func (AzureOidcConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureOidcConnectorArgs)(nil)).Elem()
}

type AzureOidcConnectorInput interface {
	pulumi.Input

	ToAzureOidcConnectorOutput() AzureOidcConnectorOutput
	ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput
}

func (*AzureOidcConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOidcConnector)(nil)).Elem()
}

func (i *AzureOidcConnector) ToAzureOidcConnectorOutput() AzureOidcConnectorOutput {
	return i.ToAzureOidcConnectorOutputWithContext(context.Background())
}

func (i *AzureOidcConnector) ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorOutput)
}

// AzureOidcConnectorArrayInput is an input type that accepts AzureOidcConnectorArray and AzureOidcConnectorArrayOutput values.
// You can construct a concrete instance of `AzureOidcConnectorArrayInput` via:
//
//	AzureOidcConnectorArray{ AzureOidcConnectorArgs{...} }
type AzureOidcConnectorArrayInput interface {
	pulumi.Input

	ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput
	ToAzureOidcConnectorArrayOutputWithContext(context.Context) AzureOidcConnectorArrayOutput
}

type AzureOidcConnectorArray []AzureOidcConnectorInput

func (AzureOidcConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureOidcConnector)(nil)).Elem()
}

func (i AzureOidcConnectorArray) ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput {
	return i.ToAzureOidcConnectorArrayOutputWithContext(context.Background())
}

func (i AzureOidcConnectorArray) ToAzureOidcConnectorArrayOutputWithContext(ctx context.Context) AzureOidcConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorArrayOutput)
}

// AzureOidcConnectorMapInput is an input type that accepts AzureOidcConnectorMap and AzureOidcConnectorMapOutput values.
// You can construct a concrete instance of `AzureOidcConnectorMapInput` via:
//
//	AzureOidcConnectorMap{ "key": AzureOidcConnectorArgs{...} }
type AzureOidcConnectorMapInput interface {
	pulumi.Input

	ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput
	ToAzureOidcConnectorMapOutputWithContext(context.Context) AzureOidcConnectorMapOutput
}

type AzureOidcConnectorMap map[string]AzureOidcConnectorInput

func (AzureOidcConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureOidcConnector)(nil)).Elem()
}

func (i AzureOidcConnectorMap) ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput {
	return i.ToAzureOidcConnectorMapOutputWithContext(context.Background())
}

func (i AzureOidcConnectorMap) ToAzureOidcConnectorMapOutputWithContext(ctx context.Context) AzureOidcConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOidcConnectorMapOutput)
}

type AzureOidcConnectorOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorOutput) ToAzureOidcConnectorOutput() AzureOidcConnectorOutput {
	return o
}

func (o AzureOidcConnectorOutput) ToAzureOidcConnectorOutputWithContext(ctx context.Context) AzureOidcConnectorOutput {
	return o
}

// Azure AD application (client) ID.
func (o AzureOidcConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Azure AD application client secret.
func (o AzureOidcConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the Azure connector.
func (o AzureOidcConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
func (o AzureOidcConnectorOutput) ExtraOidc() pulumi.MapOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.MapOutput { return v.ExtraOidc }).(pulumi.MapOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o AzureOidcConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
func (o AzureOidcConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
func (o AzureOidcConnectorOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

// Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
func (o AzureOidcConnectorOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

// Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
func (o AzureOidcConnectorOutput) UserNameSource() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureOidcConnector) pulumi.StringPtrOutput { return v.UserNameSource }).(pulumi.StringPtrOutput)
}

type AzureOidcConnectorArrayOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorArrayOutput) ToAzureOidcConnectorArrayOutput() AzureOidcConnectorArrayOutput {
	return o
}

func (o AzureOidcConnectorArrayOutput) ToAzureOidcConnectorArrayOutputWithContext(ctx context.Context) AzureOidcConnectorArrayOutput {
	return o
}

func (o AzureOidcConnectorArrayOutput) Index(i pulumi.IntInput) AzureOidcConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AzureOidcConnector {
		return vs[0].([]*AzureOidcConnector)[vs[1].(int)]
	}).(AzureOidcConnectorOutput)
}

type AzureOidcConnectorMapOutput struct{ *pulumi.OutputState }

func (AzureOidcConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureOidcConnector)(nil)).Elem()
}

func (o AzureOidcConnectorMapOutput) ToAzureOidcConnectorMapOutput() AzureOidcConnectorMapOutput {
	return o
}

func (o AzureOidcConnectorMapOutput) ToAzureOidcConnectorMapOutputWithContext(ctx context.Context) AzureOidcConnectorMapOutput {
	return o
}

func (o AzureOidcConnectorMapOutput) MapIndex(k pulumi.StringInput) AzureOidcConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AzureOidcConnector {
		return vs[0].(map[string]*AzureOidcConnector)[vs[1].(string)]
	}).(AzureOidcConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorInput)(nil)).Elem(), &AzureOidcConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorArrayInput)(nil)).Elem(), AzureOidcConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOidcConnectorMapInput)(nil)).Elem(), AzureOidcConnectorMap{})
	pulumi.RegisterOutputType(AzureOidcConnectorOutput{})
	pulumi.RegisterOutputType(AzureOidcConnectorArrayOutput{})
	pulumi.RegisterOutputType(AzureOidcConnectorMapOutput{})
}
