// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an Azure AD/Entra ID connector in Dex using the Microsoft-specific connector (type: microsoft). This connector provides Microsoft-specific features like group filtering and domain restrictions.
type AzureMicrosoftConnector struct {
	pulumi.CustomResourceState

	// Azure AD application (client) ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Azure AD application client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the Azure Microsoft connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
	Groups pulumi.StringPtrOutput `pulumi:"groups"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// Redirect URI registered in Azure AD. Must match Dex's callback URL.
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
	Tenant pulumi.StringOutput `pulumi:"tenant"`
}

// NewAzureMicrosoftConnector registers a new resource with the given unique name, arguments, and options.
func NewAzureMicrosoftConnector(ctx *pulumi.Context,
	name string, args *AzureMicrosoftConnectorArgs, opts ...pulumi.ResourceOption) (*AzureMicrosoftConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.Tenant == nil {
		return nil, errors.New("invalid value for required argument 'Tenant'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AzureMicrosoftConnector
	err := ctx.RegisterResource("dex:resources:AzureMicrosoftConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureMicrosoftConnector gets an existing AzureMicrosoftConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureMicrosoftConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureMicrosoftConnectorState, opts ...pulumi.ResourceOption) (*AzureMicrosoftConnector, error) {
	var resource AzureMicrosoftConnector
	err := ctx.ReadResource("dex:resources:AzureMicrosoftConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureMicrosoftConnector resources.
type azureMicrosoftConnectorState struct {
}

type AzureMicrosoftConnectorState struct {
}

func (AzureMicrosoftConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureMicrosoftConnectorState)(nil)).Elem()
}

type azureMicrosoftConnectorArgs struct {
	// Azure AD application (client) ID.
	ClientId string `pulumi:"clientId"`
	// Azure AD application client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the Azure Microsoft connector.
	ConnectorId string `pulumi:"connectorId"`
	// Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
	Groups *string `pulumi:"groups"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// Redirect URI registered in Azure AD. Must match Dex's callback URL.
	RedirectUri string `pulumi:"redirectUri"`
	// Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
	Tenant string `pulumi:"tenant"`
}

// The set of arguments for constructing a AzureMicrosoftConnector resource.
type AzureMicrosoftConnectorArgs struct {
	// Azure AD application (client) ID.
	ClientId pulumi.StringInput
	// Azure AD application client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the Azure Microsoft connector.
	ConnectorId pulumi.StringInput
	// Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
	Groups pulumi.StringPtrInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// Redirect URI registered in Azure AD. Must match Dex's callback URL.
	RedirectUri pulumi.StringInput
	// Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
	Tenant pulumi.StringInput
}

func (AzureMicrosoftConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureMicrosoftConnectorArgs)(nil)).Elem()
}

type AzureMicrosoftConnectorInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput
	ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput
}

func (*AzureMicrosoftConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMicrosoftConnector)(nil)).Elem()
}

func (i *AzureMicrosoftConnector) ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput {
	return i.ToAzureMicrosoftConnectorOutputWithContext(context.Background())
}

func (i *AzureMicrosoftConnector) ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorOutput)
}

// AzureMicrosoftConnectorArrayInput is an input type that accepts AzureMicrosoftConnectorArray and AzureMicrosoftConnectorArrayOutput values.
// You can construct a concrete instance of `AzureMicrosoftConnectorArrayInput` via:
//
//	AzureMicrosoftConnectorArray{ AzureMicrosoftConnectorArgs{...} }
type AzureMicrosoftConnectorArrayInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput
	ToAzureMicrosoftConnectorArrayOutputWithContext(context.Context) AzureMicrosoftConnectorArrayOutput
}

type AzureMicrosoftConnectorArray []AzureMicrosoftConnectorInput

func (AzureMicrosoftConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureMicrosoftConnector)(nil)).Elem()
}

func (i AzureMicrosoftConnectorArray) ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput {
	return i.ToAzureMicrosoftConnectorArrayOutputWithContext(context.Background())
}

func (i AzureMicrosoftConnectorArray) ToAzureMicrosoftConnectorArrayOutputWithContext(ctx context.Context) AzureMicrosoftConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorArrayOutput)
}

// AzureMicrosoftConnectorMapInput is an input type that accepts AzureMicrosoftConnectorMap and AzureMicrosoftConnectorMapOutput values.
// You can construct a concrete instance of `AzureMicrosoftConnectorMapInput` via:
//
//	AzureMicrosoftConnectorMap{ "key": AzureMicrosoftConnectorArgs{...} }
type AzureMicrosoftConnectorMapInput interface {
	pulumi.Input

	ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput
	ToAzureMicrosoftConnectorMapOutputWithContext(context.Context) AzureMicrosoftConnectorMapOutput
}

type AzureMicrosoftConnectorMap map[string]AzureMicrosoftConnectorInput

func (AzureMicrosoftConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureMicrosoftConnector)(nil)).Elem()
}

func (i AzureMicrosoftConnectorMap) ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput {
	return i.ToAzureMicrosoftConnectorMapOutputWithContext(context.Background())
}

func (i AzureMicrosoftConnectorMap) ToAzureMicrosoftConnectorMapOutputWithContext(ctx context.Context) AzureMicrosoftConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMicrosoftConnectorMapOutput)
}

type AzureMicrosoftConnectorOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorOutput) ToAzureMicrosoftConnectorOutput() AzureMicrosoftConnectorOutput {
	return o
}

func (o AzureMicrosoftConnectorOutput) ToAzureMicrosoftConnectorOutputWithContext(ctx context.Context) AzureMicrosoftConnectorOutput {
	return o
}

// Azure AD application (client) ID.
func (o AzureMicrosoftConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Azure AD application client secret.
func (o AzureMicrosoftConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the Azure Microsoft connector.
func (o AzureMicrosoftConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// Name of the claim that contains group memberships (e.g., 'groups'). Used for group-based access control.
func (o AzureMicrosoftConnectorOutput) Groups() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringPtrOutput { return v.Groups }).(pulumi.StringPtrOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o AzureMicrosoftConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Redirect URI registered in Azure AD. Must match Dex's callback URL.
func (o AzureMicrosoftConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// Azure AD tenant identifier. Can be 'common' (any Azure AD account), 'organizations' (any organizational account), or a specific tenant ID (UUID format).
func (o AzureMicrosoftConnectorOutput) Tenant() pulumi.StringOutput {
	return o.ApplyT(func(v *AzureMicrosoftConnector) pulumi.StringOutput { return v.Tenant }).(pulumi.StringOutput)
}

type AzureMicrosoftConnectorArrayOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorArrayOutput) ToAzureMicrosoftConnectorArrayOutput() AzureMicrosoftConnectorArrayOutput {
	return o
}

func (o AzureMicrosoftConnectorArrayOutput) ToAzureMicrosoftConnectorArrayOutputWithContext(ctx context.Context) AzureMicrosoftConnectorArrayOutput {
	return o
}

func (o AzureMicrosoftConnectorArrayOutput) Index(i pulumi.IntInput) AzureMicrosoftConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AzureMicrosoftConnector {
		return vs[0].([]*AzureMicrosoftConnector)[vs[1].(int)]
	}).(AzureMicrosoftConnectorOutput)
}

type AzureMicrosoftConnectorMapOutput struct{ *pulumi.OutputState }

func (AzureMicrosoftConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AzureMicrosoftConnector)(nil)).Elem()
}

func (o AzureMicrosoftConnectorMapOutput) ToAzureMicrosoftConnectorMapOutput() AzureMicrosoftConnectorMapOutput {
	return o
}

func (o AzureMicrosoftConnectorMapOutput) ToAzureMicrosoftConnectorMapOutputWithContext(ctx context.Context) AzureMicrosoftConnectorMapOutput {
	return o
}

func (o AzureMicrosoftConnectorMapOutput) MapIndex(k pulumi.StringInput) AzureMicrosoftConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AzureMicrosoftConnector {
		return vs[0].(map[string]*AzureMicrosoftConnector)[vs[1].(string)]
	}).(AzureMicrosoftConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorInput)(nil)).Elem(), &AzureMicrosoftConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorArrayInput)(nil)).Elem(), AzureMicrosoftConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMicrosoftConnectorMapInput)(nil)).Elem(), AzureMicrosoftConnectorMap{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorOutput{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorArrayOutput{})
	pulumi.RegisterOutputType(AzureMicrosoftConnectorMapOutput{})
}
