// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages an AWS Cognito user pool connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their AWS Cognito credentials.
type CognitoOidcConnector struct {
	pulumi.CustomResourceState

	// Cognito app client ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Cognito app client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the Cognito connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc pulumi.MapOutput `pulumi:"extraOidc"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// Redirect URI registered in Cognito. Must match Dex's callback URL.
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
	Region pulumi.StringOutput `pulumi:"region"`
	// OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
	Scopes pulumi.StringArrayOutput `pulumi:"scopes"`
	// Source for the username claim. Valid values: 'email' or 'sub' (subject).
	UserNameSource pulumi.StringPtrOutput `pulumi:"userNameSource"`
	// AWS Cognito user pool ID.
	UserPoolId pulumi.StringOutput `pulumi:"userPoolId"`
}

// NewCognitoOidcConnector registers a new resource with the given unique name, arguments, and options.
func NewCognitoOidcConnector(ctx *pulumi.Context,
	name string, args *CognitoOidcConnectorArgs, opts ...pulumi.ResourceOption) (*CognitoOidcConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.UserPoolId == nil {
		return nil, errors.New("invalid value for required argument 'UserPoolId'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CognitoOidcConnector
	err := ctx.RegisterResource("dex:resources:CognitoOidcConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCognitoOidcConnector gets an existing CognitoOidcConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCognitoOidcConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CognitoOidcConnectorState, opts ...pulumi.ResourceOption) (*CognitoOidcConnector, error) {
	var resource CognitoOidcConnector
	err := ctx.ReadResource("dex:resources:CognitoOidcConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CognitoOidcConnector resources.
type cognitoOidcConnectorState struct {
}

type CognitoOidcConnectorState struct {
}

func (CognitoOidcConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoOidcConnectorState)(nil)).Elem()
}

type cognitoOidcConnectorArgs struct {
	// Cognito app client ID.
	ClientId string `pulumi:"clientId"`
	// Cognito app client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the Cognito connector.
	ConnectorId string `pulumi:"connectorId"`
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc map[string]interface{} `pulumi:"extraOidc"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// Redirect URI registered in Cognito. Must match Dex's callback URL.
	RedirectUri string `pulumi:"redirectUri"`
	// AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
	Region string `pulumi:"region"`
	// OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
	Scopes []string `pulumi:"scopes"`
	// Source for the username claim. Valid values: 'email' or 'sub' (subject).
	UserNameSource *string `pulumi:"userNameSource"`
	// AWS Cognito user pool ID.
	UserPoolId string `pulumi:"userPoolId"`
}

// The set of arguments for constructing a CognitoOidcConnector resource.
type CognitoOidcConnectorArgs struct {
	// Cognito app client ID.
	ClientId pulumi.StringInput
	// Cognito app client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the Cognito connector.
	ConnectorId pulumi.StringInput
	// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
	ExtraOidc pulumi.MapInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// Redirect URI registered in Cognito. Must match Dex's callback URL.
	RedirectUri pulumi.StringInput
	// AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
	Region pulumi.StringInput
	// OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
	Scopes pulumi.StringArrayInput
	// Source for the username claim. Valid values: 'email' or 'sub' (subject).
	UserNameSource pulumi.StringPtrInput
	// AWS Cognito user pool ID.
	UserPoolId pulumi.StringInput
}

func (CognitoOidcConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoOidcConnectorArgs)(nil)).Elem()
}

type CognitoOidcConnectorInput interface {
	pulumi.Input

	ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput
	ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput
}

func (*CognitoOidcConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoOidcConnector)(nil)).Elem()
}

func (i *CognitoOidcConnector) ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput {
	return i.ToCognitoOidcConnectorOutputWithContext(context.Background())
}

func (i *CognitoOidcConnector) ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorOutput)
}

// CognitoOidcConnectorArrayInput is an input type that accepts CognitoOidcConnectorArray and CognitoOidcConnectorArrayOutput values.
// You can construct a concrete instance of `CognitoOidcConnectorArrayInput` via:
//
//	CognitoOidcConnectorArray{ CognitoOidcConnectorArgs{...} }
type CognitoOidcConnectorArrayInput interface {
	pulumi.Input

	ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput
	ToCognitoOidcConnectorArrayOutputWithContext(context.Context) CognitoOidcConnectorArrayOutput
}

type CognitoOidcConnectorArray []CognitoOidcConnectorInput

func (CognitoOidcConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoOidcConnector)(nil)).Elem()
}

func (i CognitoOidcConnectorArray) ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput {
	return i.ToCognitoOidcConnectorArrayOutputWithContext(context.Background())
}

func (i CognitoOidcConnectorArray) ToCognitoOidcConnectorArrayOutputWithContext(ctx context.Context) CognitoOidcConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorArrayOutput)
}

// CognitoOidcConnectorMapInput is an input type that accepts CognitoOidcConnectorMap and CognitoOidcConnectorMapOutput values.
// You can construct a concrete instance of `CognitoOidcConnectorMapInput` via:
//
//	CognitoOidcConnectorMap{ "key": CognitoOidcConnectorArgs{...} }
type CognitoOidcConnectorMapInput interface {
	pulumi.Input

	ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput
	ToCognitoOidcConnectorMapOutputWithContext(context.Context) CognitoOidcConnectorMapOutput
}

type CognitoOidcConnectorMap map[string]CognitoOidcConnectorInput

func (CognitoOidcConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoOidcConnector)(nil)).Elem()
}

func (i CognitoOidcConnectorMap) ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput {
	return i.ToCognitoOidcConnectorMapOutputWithContext(context.Background())
}

func (i CognitoOidcConnectorMap) ToCognitoOidcConnectorMapOutputWithContext(ctx context.Context) CognitoOidcConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoOidcConnectorMapOutput)
}

type CognitoOidcConnectorOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorOutput) ToCognitoOidcConnectorOutput() CognitoOidcConnectorOutput {
	return o
}

func (o CognitoOidcConnectorOutput) ToCognitoOidcConnectorOutputWithContext(ctx context.Context) CognitoOidcConnectorOutput {
	return o
}

// Cognito app client ID.
func (o CognitoOidcConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Cognito app client secret.
func (o CognitoOidcConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the Cognito connector.
func (o CognitoOidcConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// Additional OIDC configuration fields as key-value pairs for advanced scenarios.
func (o CognitoOidcConnectorOutput) ExtraOidc() pulumi.MapOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.MapOutput { return v.ExtraOidc }).(pulumi.MapOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o CognitoOidcConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Redirect URI registered in Cognito. Must match Dex's callback URL.
func (o CognitoOidcConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// AWS region where the Cognito user pool is located (e.g., 'us-east-1', 'eu-west-1').
func (o CognitoOidcConnectorOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// OIDC scopes to request from Cognito. Defaults to ['openid', 'email', 'profile'] if not specified.
func (o CognitoOidcConnectorOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

// Source for the username claim. Valid values: 'email' or 'sub' (subject).
func (o CognitoOidcConnectorOutput) UserNameSource() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringPtrOutput { return v.UserNameSource }).(pulumi.StringPtrOutput)
}

// AWS Cognito user pool ID.
func (o CognitoOidcConnectorOutput) UserPoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoOidcConnector) pulumi.StringOutput { return v.UserPoolId }).(pulumi.StringOutput)
}

type CognitoOidcConnectorArrayOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorArrayOutput) ToCognitoOidcConnectorArrayOutput() CognitoOidcConnectorArrayOutput {
	return o
}

func (o CognitoOidcConnectorArrayOutput) ToCognitoOidcConnectorArrayOutputWithContext(ctx context.Context) CognitoOidcConnectorArrayOutput {
	return o
}

func (o CognitoOidcConnectorArrayOutput) Index(i pulumi.IntInput) CognitoOidcConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CognitoOidcConnector {
		return vs[0].([]*CognitoOidcConnector)[vs[1].(int)]
	}).(CognitoOidcConnectorOutput)
}

type CognitoOidcConnectorMapOutput struct{ *pulumi.OutputState }

func (CognitoOidcConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoOidcConnector)(nil)).Elem()
}

func (o CognitoOidcConnectorMapOutput) ToCognitoOidcConnectorMapOutput() CognitoOidcConnectorMapOutput {
	return o
}

func (o CognitoOidcConnectorMapOutput) ToCognitoOidcConnectorMapOutputWithContext(ctx context.Context) CognitoOidcConnectorMapOutput {
	return o
}

func (o CognitoOidcConnectorMapOutput) MapIndex(k pulumi.StringInput) CognitoOidcConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CognitoOidcConnector {
		return vs[0].(map[string]*CognitoOidcConnector)[vs[1].(string)]
	}).(CognitoOidcConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorInput)(nil)).Elem(), &CognitoOidcConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorArrayInput)(nil)).Elem(), CognitoOidcConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoOidcConnectorMapInput)(nil)).Elem(), CognitoOidcConnectorMap{})
	pulumi.RegisterOutputType(CognitoOidcConnectorOutput{})
	pulumi.RegisterOutputType(CognitoOidcConnectorArrayOutput{})
	pulumi.RegisterOutputType(CognitoOidcConnectorMapOutput{})
}
