// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a GitHub connector in Dex. This connector allows users to authenticate using their GitHub accounts and supports organization and team-based access control.
type GitHubConnector struct {
	pulumi.CustomResourceState

	// GitHub OAuth app client ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// GitHub OAuth app client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the GitHub connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
	HostName pulumi.StringPtrOutput `pulumi:"hostName"`
	// If true, load all groups (teams) the user is a member of. Defaults to false.
	LoadAllGroups pulumi.BoolPtrOutput `pulumi:"loadAllGroups"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
	Orgs GitHubOrgArrayOutput `pulumi:"orgs"`
	// Preferred email domain. If set, users with emails in this domain will be preferred.
	PreferredEmailDomain pulumi.StringPtrOutput `pulumi:"preferredEmailDomain"`
	// Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
	RootCA pulumi.StringPtrOutput `pulumi:"rootCA"`
	// Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
	TeamNameField pulumi.StringPtrOutput `pulumi:"teamNameField"`
	// If true, use GitHub login username as the user ID. Defaults to false.
	UseLoginAsID pulumi.BoolPtrOutput `pulumi:"useLoginAsID"`
}

// NewGitHubConnector registers a new resource with the given unique name, arguments, and options.
func NewGitHubConnector(ctx *pulumi.Context,
	name string, args *GitHubConnectorArgs, opts ...pulumi.ResourceOption) (*GitHubConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GitHubConnector
	err := ctx.RegisterResource("dex:resources:GitHubConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGitHubConnector gets an existing GitHubConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGitHubConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GitHubConnectorState, opts ...pulumi.ResourceOption) (*GitHubConnector, error) {
	var resource GitHubConnector
	err := ctx.ReadResource("dex:resources:GitHubConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GitHubConnector resources.
type gitHubConnectorState struct {
}

type GitHubConnectorState struct {
}

func (GitHubConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*gitHubConnectorState)(nil)).Elem()
}

type gitHubConnectorArgs struct {
	// GitHub OAuth app client ID.
	ClientId string `pulumi:"clientId"`
	// GitHub OAuth app client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the GitHub connector.
	ConnectorId string `pulumi:"connectorId"`
	// GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
	HostName *string `pulumi:"hostName"`
	// If true, load all groups (teams) the user is a member of. Defaults to false.
	LoadAllGroups *bool `pulumi:"loadAllGroups"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
	Orgs []GitHubOrg `pulumi:"orgs"`
	// Preferred email domain. If set, users with emails in this domain will be preferred.
	PreferredEmailDomain *string `pulumi:"preferredEmailDomain"`
	// Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
	RedirectUri string `pulumi:"redirectUri"`
	// Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
	RootCA *string `pulumi:"rootCA"`
	// Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
	TeamNameField *string `pulumi:"teamNameField"`
	// If true, use GitHub login username as the user ID. Defaults to false.
	UseLoginAsID *bool `pulumi:"useLoginAsID"`
}

// The set of arguments for constructing a GitHubConnector resource.
type GitHubConnectorArgs struct {
	// GitHub OAuth app client ID.
	ClientId pulumi.StringInput
	// GitHub OAuth app client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the GitHub connector.
	ConnectorId pulumi.StringInput
	// GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
	HostName pulumi.StringPtrInput
	// If true, load all groups (teams) the user is a member of. Defaults to false.
	LoadAllGroups pulumi.BoolPtrInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
	Orgs GitHubOrgArrayInput
	// Preferred email domain. If set, users with emails in this domain will be preferred.
	PreferredEmailDomain pulumi.StringPtrInput
	// Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringInput
	// Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
	RootCA pulumi.StringPtrInput
	// Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
	TeamNameField pulumi.StringPtrInput
	// If true, use GitHub login username as the user ID. Defaults to false.
	UseLoginAsID pulumi.BoolPtrInput
}

func (GitHubConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gitHubConnectorArgs)(nil)).Elem()
}

type GitHubConnectorInput interface {
	pulumi.Input

	ToGitHubConnectorOutput() GitHubConnectorOutput
	ToGitHubConnectorOutputWithContext(ctx context.Context) GitHubConnectorOutput
}

func (*GitHubConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**GitHubConnector)(nil)).Elem()
}

func (i *GitHubConnector) ToGitHubConnectorOutput() GitHubConnectorOutput {
	return i.ToGitHubConnectorOutputWithContext(context.Background())
}

func (i *GitHubConnector) ToGitHubConnectorOutputWithContext(ctx context.Context) GitHubConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitHubConnectorOutput)
}

// GitHubConnectorArrayInput is an input type that accepts GitHubConnectorArray and GitHubConnectorArrayOutput values.
// You can construct a concrete instance of `GitHubConnectorArrayInput` via:
//
//	GitHubConnectorArray{ GitHubConnectorArgs{...} }
type GitHubConnectorArrayInput interface {
	pulumi.Input

	ToGitHubConnectorArrayOutput() GitHubConnectorArrayOutput
	ToGitHubConnectorArrayOutputWithContext(context.Context) GitHubConnectorArrayOutput
}

type GitHubConnectorArray []GitHubConnectorInput

func (GitHubConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitHubConnector)(nil)).Elem()
}

func (i GitHubConnectorArray) ToGitHubConnectorArrayOutput() GitHubConnectorArrayOutput {
	return i.ToGitHubConnectorArrayOutputWithContext(context.Background())
}

func (i GitHubConnectorArray) ToGitHubConnectorArrayOutputWithContext(ctx context.Context) GitHubConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitHubConnectorArrayOutput)
}

// GitHubConnectorMapInput is an input type that accepts GitHubConnectorMap and GitHubConnectorMapOutput values.
// You can construct a concrete instance of `GitHubConnectorMapInput` via:
//
//	GitHubConnectorMap{ "key": GitHubConnectorArgs{...} }
type GitHubConnectorMapInput interface {
	pulumi.Input

	ToGitHubConnectorMapOutput() GitHubConnectorMapOutput
	ToGitHubConnectorMapOutputWithContext(context.Context) GitHubConnectorMapOutput
}

type GitHubConnectorMap map[string]GitHubConnectorInput

func (GitHubConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitHubConnector)(nil)).Elem()
}

func (i GitHubConnectorMap) ToGitHubConnectorMapOutput() GitHubConnectorMapOutput {
	return i.ToGitHubConnectorMapOutputWithContext(context.Background())
}

func (i GitHubConnectorMap) ToGitHubConnectorMapOutputWithContext(ctx context.Context) GitHubConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitHubConnectorMapOutput)
}

type GitHubConnectorOutput struct{ *pulumi.OutputState }

func (GitHubConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GitHubConnector)(nil)).Elem()
}

func (o GitHubConnectorOutput) ToGitHubConnectorOutput() GitHubConnectorOutput {
	return o
}

func (o GitHubConnectorOutput) ToGitHubConnectorOutputWithContext(ctx context.Context) GitHubConnectorOutput {
	return o
}

// GitHub OAuth app client ID.
func (o GitHubConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// GitHub OAuth app client secret.
func (o GitHubConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the GitHub connector.
func (o GitHubConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
func (o GitHubConnectorOutput) HostName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringPtrOutput { return v.HostName }).(pulumi.StringPtrOutput)
}

// If true, load all groups (teams) the user is a member of. Defaults to false.
func (o GitHubConnectorOutput) LoadAllGroups() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.BoolPtrOutput { return v.LoadAllGroups }).(pulumi.BoolPtrOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o GitHubConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
func (o GitHubConnectorOutput) Orgs() GitHubOrgArrayOutput {
	return o.ApplyT(func(v *GitHubConnector) GitHubOrgArrayOutput { return v.Orgs }).(GitHubOrgArrayOutput)
}

// Preferred email domain. If set, users with emails in this domain will be preferred.
func (o GitHubConnectorOutput) PreferredEmailDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringPtrOutput { return v.PreferredEmailDomain }).(pulumi.StringPtrOutput)
}

// Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
func (o GitHubConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
func (o GitHubConnectorOutput) RootCA() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringPtrOutput { return v.RootCA }).(pulumi.StringPtrOutput)
}

// Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
func (o GitHubConnectorOutput) TeamNameField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.StringPtrOutput { return v.TeamNameField }).(pulumi.StringPtrOutput)
}

// If true, use GitHub login username as the user ID. Defaults to false.
func (o GitHubConnectorOutput) UseLoginAsID() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GitHubConnector) pulumi.BoolPtrOutput { return v.UseLoginAsID }).(pulumi.BoolPtrOutput)
}

type GitHubConnectorArrayOutput struct{ *pulumi.OutputState }

func (GitHubConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitHubConnector)(nil)).Elem()
}

func (o GitHubConnectorArrayOutput) ToGitHubConnectorArrayOutput() GitHubConnectorArrayOutput {
	return o
}

func (o GitHubConnectorArrayOutput) ToGitHubConnectorArrayOutputWithContext(ctx context.Context) GitHubConnectorArrayOutput {
	return o
}

func (o GitHubConnectorArrayOutput) Index(i pulumi.IntInput) GitHubConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GitHubConnector {
		return vs[0].([]*GitHubConnector)[vs[1].(int)]
	}).(GitHubConnectorOutput)
}

type GitHubConnectorMapOutput struct{ *pulumi.OutputState }

func (GitHubConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitHubConnector)(nil)).Elem()
}

func (o GitHubConnectorMapOutput) ToGitHubConnectorMapOutput() GitHubConnectorMapOutput {
	return o
}

func (o GitHubConnectorMapOutput) ToGitHubConnectorMapOutputWithContext(ctx context.Context) GitHubConnectorMapOutput {
	return o
}

func (o GitHubConnectorMapOutput) MapIndex(k pulumi.StringInput) GitHubConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GitHubConnector {
		return vs[0].(map[string]*GitHubConnector)[vs[1].(string)]
	}).(GitHubConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GitHubConnectorInput)(nil)).Elem(), &GitHubConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitHubConnectorArrayInput)(nil)).Elem(), GitHubConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitHubConnectorMapInput)(nil)).Elem(), GitHubConnectorMap{})
	pulumi.RegisterOutputType(GitHubConnectorOutput{})
	pulumi.RegisterOutputType(GitHubConnectorArrayOutput{})
	pulumi.RegisterOutputType(GitHubConnectorMapOutput{})
}
