// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a GitLab connector in Dex. This connector allows users to authenticate using their GitLab accounts and supports group-based access control.
type GitLabConnector struct {
	pulumi.CustomResourceState

	// GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
	BaseURL pulumi.StringPtrOutput `pulumi:"baseURL"`
	// GitLab OAuth application client ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// GitLab OAuth application client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the GitLab connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// If true, request 'read_api' scope to fetch group memberships. Defaults to false.
	GetGroupsPermission pulumi.BoolPtrOutput `pulumi:"getGroupsPermission"`
	// List of GitLab group names. Only users in these groups will be allowed to authenticate.
	Groups pulumi.StringArrayOutput `pulumi:"groups"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// If true, use GitLab username as the user ID. Defaults to false.
	UseLoginAsID pulumi.BoolPtrOutput `pulumi:"useLoginAsID"`
}

// NewGitLabConnector registers a new resource with the given unique name, arguments, and options.
func NewGitLabConnector(ctx *pulumi.Context,
	name string, args *GitLabConnectorArgs, opts ...pulumi.ResourceOption) (*GitLabConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GitLabConnector
	err := ctx.RegisterResource("dex:resources:GitLabConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGitLabConnector gets an existing GitLabConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGitLabConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GitLabConnectorState, opts ...pulumi.ResourceOption) (*GitLabConnector, error) {
	var resource GitLabConnector
	err := ctx.ReadResource("dex:resources:GitLabConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GitLabConnector resources.
type gitLabConnectorState struct {
}

type GitLabConnectorState struct {
}

func (GitLabConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*gitLabConnectorState)(nil)).Elem()
}

type gitLabConnectorArgs struct {
	// GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
	BaseURL *string `pulumi:"baseURL"`
	// GitLab OAuth application client ID.
	ClientId string `pulumi:"clientId"`
	// GitLab OAuth application client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the GitLab connector.
	ConnectorId string `pulumi:"connectorId"`
	// If true, request 'read_api' scope to fetch group memberships. Defaults to false.
	GetGroupsPermission *bool `pulumi:"getGroupsPermission"`
	// List of GitLab group names. Only users in these groups will be allowed to authenticate.
	Groups []string `pulumi:"groups"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
	RedirectUri string `pulumi:"redirectUri"`
	// If true, use GitLab username as the user ID. Defaults to false.
	UseLoginAsID *bool `pulumi:"useLoginAsID"`
}

// The set of arguments for constructing a GitLabConnector resource.
type GitLabConnectorArgs struct {
	// GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
	BaseURL pulumi.StringPtrInput
	// GitLab OAuth application client ID.
	ClientId pulumi.StringInput
	// GitLab OAuth application client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the GitLab connector.
	ConnectorId pulumi.StringInput
	// If true, request 'read_api' scope to fetch group memberships. Defaults to false.
	GetGroupsPermission pulumi.BoolPtrInput
	// List of GitLab group names. Only users in these groups will be allowed to authenticate.
	Groups pulumi.StringArrayInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringInput
	// If true, use GitLab username as the user ID. Defaults to false.
	UseLoginAsID pulumi.BoolPtrInput
}

func (GitLabConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gitLabConnectorArgs)(nil)).Elem()
}

type GitLabConnectorInput interface {
	pulumi.Input

	ToGitLabConnectorOutput() GitLabConnectorOutput
	ToGitLabConnectorOutputWithContext(ctx context.Context) GitLabConnectorOutput
}

func (*GitLabConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**GitLabConnector)(nil)).Elem()
}

func (i *GitLabConnector) ToGitLabConnectorOutput() GitLabConnectorOutput {
	return i.ToGitLabConnectorOutputWithContext(context.Background())
}

func (i *GitLabConnector) ToGitLabConnectorOutputWithContext(ctx context.Context) GitLabConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitLabConnectorOutput)
}

// GitLabConnectorArrayInput is an input type that accepts GitLabConnectorArray and GitLabConnectorArrayOutput values.
// You can construct a concrete instance of `GitLabConnectorArrayInput` via:
//
//	GitLabConnectorArray{ GitLabConnectorArgs{...} }
type GitLabConnectorArrayInput interface {
	pulumi.Input

	ToGitLabConnectorArrayOutput() GitLabConnectorArrayOutput
	ToGitLabConnectorArrayOutputWithContext(context.Context) GitLabConnectorArrayOutput
}

type GitLabConnectorArray []GitLabConnectorInput

func (GitLabConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitLabConnector)(nil)).Elem()
}

func (i GitLabConnectorArray) ToGitLabConnectorArrayOutput() GitLabConnectorArrayOutput {
	return i.ToGitLabConnectorArrayOutputWithContext(context.Background())
}

func (i GitLabConnectorArray) ToGitLabConnectorArrayOutputWithContext(ctx context.Context) GitLabConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitLabConnectorArrayOutput)
}

// GitLabConnectorMapInput is an input type that accepts GitLabConnectorMap and GitLabConnectorMapOutput values.
// You can construct a concrete instance of `GitLabConnectorMapInput` via:
//
//	GitLabConnectorMap{ "key": GitLabConnectorArgs{...} }
type GitLabConnectorMapInput interface {
	pulumi.Input

	ToGitLabConnectorMapOutput() GitLabConnectorMapOutput
	ToGitLabConnectorMapOutputWithContext(context.Context) GitLabConnectorMapOutput
}

type GitLabConnectorMap map[string]GitLabConnectorInput

func (GitLabConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitLabConnector)(nil)).Elem()
}

func (i GitLabConnectorMap) ToGitLabConnectorMapOutput() GitLabConnectorMapOutput {
	return i.ToGitLabConnectorMapOutputWithContext(context.Background())
}

func (i GitLabConnectorMap) ToGitLabConnectorMapOutputWithContext(ctx context.Context) GitLabConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GitLabConnectorMapOutput)
}

type GitLabConnectorOutput struct{ *pulumi.OutputState }

func (GitLabConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GitLabConnector)(nil)).Elem()
}

func (o GitLabConnectorOutput) ToGitLabConnectorOutput() GitLabConnectorOutput {
	return o
}

func (o GitLabConnectorOutput) ToGitLabConnectorOutputWithContext(ctx context.Context) GitLabConnectorOutput {
	return o
}

// GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
func (o GitLabConnectorOutput) BaseURL() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringPtrOutput { return v.BaseURL }).(pulumi.StringPtrOutput)
}

// GitLab OAuth application client ID.
func (o GitLabConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// GitLab OAuth application client secret.
func (o GitLabConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the GitLab connector.
func (o GitLabConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// If true, request 'read_api' scope to fetch group memberships. Defaults to false.
func (o GitLabConnectorOutput) GetGroupsPermission() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.BoolPtrOutput { return v.GetGroupsPermission }).(pulumi.BoolPtrOutput)
}

// List of GitLab group names. Only users in these groups will be allowed to authenticate.
func (o GitLabConnectorOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringArrayOutput { return v.Groups }).(pulumi.StringArrayOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o GitLabConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
func (o GitLabConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// If true, use GitLab username as the user ID. Defaults to false.
func (o GitLabConnectorOutput) UseLoginAsID() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GitLabConnector) pulumi.BoolPtrOutput { return v.UseLoginAsID }).(pulumi.BoolPtrOutput)
}

type GitLabConnectorArrayOutput struct{ *pulumi.OutputState }

func (GitLabConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GitLabConnector)(nil)).Elem()
}

func (o GitLabConnectorArrayOutput) ToGitLabConnectorArrayOutput() GitLabConnectorArrayOutput {
	return o
}

func (o GitLabConnectorArrayOutput) ToGitLabConnectorArrayOutputWithContext(ctx context.Context) GitLabConnectorArrayOutput {
	return o
}

func (o GitLabConnectorArrayOutput) Index(i pulumi.IntInput) GitLabConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GitLabConnector {
		return vs[0].([]*GitLabConnector)[vs[1].(int)]
	}).(GitLabConnectorOutput)
}

type GitLabConnectorMapOutput struct{ *pulumi.OutputState }

func (GitLabConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GitLabConnector)(nil)).Elem()
}

func (o GitLabConnectorMapOutput) ToGitLabConnectorMapOutput() GitLabConnectorMapOutput {
	return o
}

func (o GitLabConnectorMapOutput) ToGitLabConnectorMapOutputWithContext(ctx context.Context) GitLabConnectorMapOutput {
	return o
}

func (o GitLabConnectorMapOutput) MapIndex(k pulumi.StringInput) GitLabConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GitLabConnector {
		return vs[0].(map[string]*GitLabConnector)[vs[1].(string)]
	}).(GitLabConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GitLabConnectorInput)(nil)).Elem(), &GitLabConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitLabConnectorArrayInput)(nil)).Elem(), GitLabConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GitLabConnectorMapInput)(nil)).Elem(), GitLabConnectorMap{})
	pulumi.RegisterOutputType(GitLabConnectorOutput{})
	pulumi.RegisterOutputType(GitLabConnectorArrayOutput{})
	pulumi.RegisterOutputType(GitLabConnectorMapOutput{})
}
