// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Google connector in Dex. This connector allows users to authenticate using their Google accounts and supports domain and group-based access control.
type GoogleConnector struct {
	pulumi.CustomResourceState

	// Google OAuth client ID.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Google OAuth client secret.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// Unique identifier for the Google connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
	DomainToAdminEmail pulumi.StringMapOutput `pulumi:"domainToAdminEmail"`
	// List of Google Groups. Only users in these groups will be allowed to authenticate.
	Groups pulumi.StringArrayOutput `pulumi:"groups"`
	// List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
	HostedDomains pulumi.StringArrayOutput `pulumi:"hostedDomains"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
	// OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
	PromptType pulumi.StringPtrOutput `pulumi:"promptType"`
	// Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringOutput `pulumi:"redirectUri"`
	// Path to Google service account JSON file. Required for group-based access control.
	ServiceAccountFilePath pulumi.StringPtrOutput `pulumi:"serviceAccountFilePath"`
}

// NewGoogleConnector registers a new resource with the given unique name, arguments, and options.
func NewGoogleConnector(ctx *pulumi.Context,
	name string, args *GoogleConnectorArgs, opts ...pulumi.ResourceOption) (*GoogleConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.RedirectUri == nil {
		return nil, errors.New("invalid value for required argument 'RedirectUri'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GoogleConnector
	err := ctx.RegisterResource("dex:resources:GoogleConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGoogleConnector gets an existing GoogleConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGoogleConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GoogleConnectorState, opts ...pulumi.ResourceOption) (*GoogleConnector, error) {
	var resource GoogleConnector
	err := ctx.ReadResource("dex:resources:GoogleConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GoogleConnector resources.
type googleConnectorState struct {
}

type GoogleConnectorState struct {
}

func (GoogleConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*googleConnectorState)(nil)).Elem()
}

type googleConnectorArgs struct {
	// Google OAuth client ID.
	ClientId string `pulumi:"clientId"`
	// Google OAuth client secret.
	ClientSecret string `pulumi:"clientSecret"`
	// Unique identifier for the Google connector.
	ConnectorId string `pulumi:"connectorId"`
	// Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
	DomainToAdminEmail map[string]string `pulumi:"domainToAdminEmail"`
	// List of Google Groups. Only users in these groups will be allowed to authenticate.
	Groups []string `pulumi:"groups"`
	// List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
	HostedDomains []string `pulumi:"hostedDomains"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
	// OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
	PromptType *string `pulumi:"promptType"`
	// Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
	RedirectUri string `pulumi:"redirectUri"`
	// Path to Google service account JSON file. Required for group-based access control.
	ServiceAccountFilePath *string `pulumi:"serviceAccountFilePath"`
}

// The set of arguments for constructing a GoogleConnector resource.
type GoogleConnectorArgs struct {
	// Google OAuth client ID.
	ClientId pulumi.StringInput
	// Google OAuth client secret.
	ClientSecret pulumi.StringInput
	// Unique identifier for the Google connector.
	ConnectorId pulumi.StringInput
	// Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
	DomainToAdminEmail pulumi.StringMapInput
	// List of Google Groups. Only users in these groups will be allowed to authenticate.
	Groups pulumi.StringArrayInput
	// List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
	HostedDomains pulumi.StringArrayInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
	// OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
	PromptType pulumi.StringPtrInput
	// Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
	RedirectUri pulumi.StringInput
	// Path to Google service account JSON file. Required for group-based access control.
	ServiceAccountFilePath pulumi.StringPtrInput
}

func (GoogleConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*googleConnectorArgs)(nil)).Elem()
}

type GoogleConnectorInput interface {
	pulumi.Input

	ToGoogleConnectorOutput() GoogleConnectorOutput
	ToGoogleConnectorOutputWithContext(ctx context.Context) GoogleConnectorOutput
}

func (*GoogleConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleConnector)(nil)).Elem()
}

func (i *GoogleConnector) ToGoogleConnectorOutput() GoogleConnectorOutput {
	return i.ToGoogleConnectorOutputWithContext(context.Background())
}

func (i *GoogleConnector) ToGoogleConnectorOutputWithContext(ctx context.Context) GoogleConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleConnectorOutput)
}

// GoogleConnectorArrayInput is an input type that accepts GoogleConnectorArray and GoogleConnectorArrayOutput values.
// You can construct a concrete instance of `GoogleConnectorArrayInput` via:
//
//	GoogleConnectorArray{ GoogleConnectorArgs{...} }
type GoogleConnectorArrayInput interface {
	pulumi.Input

	ToGoogleConnectorArrayOutput() GoogleConnectorArrayOutput
	ToGoogleConnectorArrayOutputWithContext(context.Context) GoogleConnectorArrayOutput
}

type GoogleConnectorArray []GoogleConnectorInput

func (GoogleConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GoogleConnector)(nil)).Elem()
}

func (i GoogleConnectorArray) ToGoogleConnectorArrayOutput() GoogleConnectorArrayOutput {
	return i.ToGoogleConnectorArrayOutputWithContext(context.Background())
}

func (i GoogleConnectorArray) ToGoogleConnectorArrayOutputWithContext(ctx context.Context) GoogleConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleConnectorArrayOutput)
}

// GoogleConnectorMapInput is an input type that accepts GoogleConnectorMap and GoogleConnectorMapOutput values.
// You can construct a concrete instance of `GoogleConnectorMapInput` via:
//
//	GoogleConnectorMap{ "key": GoogleConnectorArgs{...} }
type GoogleConnectorMapInput interface {
	pulumi.Input

	ToGoogleConnectorMapOutput() GoogleConnectorMapOutput
	ToGoogleConnectorMapOutputWithContext(context.Context) GoogleConnectorMapOutput
}

type GoogleConnectorMap map[string]GoogleConnectorInput

func (GoogleConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GoogleConnector)(nil)).Elem()
}

func (i GoogleConnectorMap) ToGoogleConnectorMapOutput() GoogleConnectorMapOutput {
	return i.ToGoogleConnectorMapOutputWithContext(context.Background())
}

func (i GoogleConnectorMap) ToGoogleConnectorMapOutputWithContext(ctx context.Context) GoogleConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleConnectorMapOutput)
}

type GoogleConnectorOutput struct{ *pulumi.OutputState }

func (GoogleConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleConnector)(nil)).Elem()
}

func (o GoogleConnectorOutput) ToGoogleConnectorOutput() GoogleConnectorOutput {
	return o
}

func (o GoogleConnectorOutput) ToGoogleConnectorOutputWithContext(ctx context.Context) GoogleConnectorOutput {
	return o
}

// Google OAuth client ID.
func (o GoogleConnectorOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Google OAuth client secret.
func (o GoogleConnectorOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// Unique identifier for the Google connector.
func (o GoogleConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
func (o GoogleConnectorOutput) DomainToAdminEmail() pulumi.StringMapOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringMapOutput { return v.DomainToAdminEmail }).(pulumi.StringMapOutput)
}

// List of Google Groups. Only users in these groups will be allowed to authenticate.
func (o GoogleConnectorOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringArrayOutput { return v.Groups }).(pulumi.StringArrayOutput)
}

// List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
func (o GoogleConnectorOutput) HostedDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringArrayOutput { return v.HostedDomains }).(pulumi.StringArrayOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o GoogleConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
func (o GoogleConnectorOutput) PromptType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringPtrOutput { return v.PromptType }).(pulumi.StringPtrOutput)
}

// Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
func (o GoogleConnectorOutput) RedirectUri() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringOutput { return v.RedirectUri }).(pulumi.StringOutput)
}

// Path to Google service account JSON file. Required for group-based access control.
func (o GoogleConnectorOutput) ServiceAccountFilePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleConnector) pulumi.StringPtrOutput { return v.ServiceAccountFilePath }).(pulumi.StringPtrOutput)
}

type GoogleConnectorArrayOutput struct{ *pulumi.OutputState }

func (GoogleConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GoogleConnector)(nil)).Elem()
}

func (o GoogleConnectorArrayOutput) ToGoogleConnectorArrayOutput() GoogleConnectorArrayOutput {
	return o
}

func (o GoogleConnectorArrayOutput) ToGoogleConnectorArrayOutputWithContext(ctx context.Context) GoogleConnectorArrayOutput {
	return o
}

func (o GoogleConnectorArrayOutput) Index(i pulumi.IntInput) GoogleConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GoogleConnector {
		return vs[0].([]*GoogleConnector)[vs[1].(int)]
	}).(GoogleConnectorOutput)
}

type GoogleConnectorMapOutput struct{ *pulumi.OutputState }

func (GoogleConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GoogleConnector)(nil)).Elem()
}

func (o GoogleConnectorMapOutput) ToGoogleConnectorMapOutput() GoogleConnectorMapOutput {
	return o
}

func (o GoogleConnectorMapOutput) ToGoogleConnectorMapOutputWithContext(ctx context.Context) GoogleConnectorMapOutput {
	return o
}

func (o GoogleConnectorMapOutput) MapIndex(k pulumi.StringInput) GoogleConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GoogleConnector {
		return vs[0].(map[string]*GoogleConnector)[vs[1].(string)]
	}).(GoogleConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleConnectorInput)(nil)).Elem(), &GoogleConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleConnectorArrayInput)(nil)).Elem(), GoogleConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleConnectorMapInput)(nil)).Elem(), GoogleConnectorMap{})
	pulumi.RegisterOutputType(GoogleConnectorOutput{})
	pulumi.RegisterOutputType(GoogleConnectorArrayOutput{})
	pulumi.RegisterOutputType(GoogleConnectorMapOutput{})
}
