// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "dex:resources:AzureMicrosoftConnector":
		r = &AzureMicrosoftConnector{}
	case "dex:resources:AzureOidcConnector":
		r = &AzureOidcConnector{}
	case "dex:resources:Client":
		r = &Client{}
	case "dex:resources:CognitoOidcConnector":
		r = &CognitoOidcConnector{}
	case "dex:resources:Connector":
		r = &Connector{}
	case "dex:resources:GitHubConnector":
		r = &GitHubConnector{}
	case "dex:resources:GitLabConnector":
		r = &GitLabConnector{}
	case "dex:resources:GoogleConnector":
		r = &GoogleConnector{}
	case "dex:resources:LocalConnector":
		r = &LocalConnector{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"dex",
		"resources",
		&module{version},
	)
}
