// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a local/builtin connector in Dex. The local connector provides username/password authentication stored in Dex's database. This is useful for testing or when you don't have an external identity provider.
type LocalConnector struct {
	pulumi.CustomResourceState

	// Unique identifier for the local connector.
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// Whether the local connector is enabled. Defaults to true.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewLocalConnector registers a new resource with the given unique name, arguments, and options.
func NewLocalConnector(ctx *pulumi.Context,
	name string, args *LocalConnectorArgs, opts ...pulumi.ResourceOption) (*LocalConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LocalConnector
	err := ctx.RegisterResource("dex:resources:LocalConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLocalConnector gets an existing LocalConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLocalConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LocalConnectorState, opts ...pulumi.ResourceOption) (*LocalConnector, error) {
	var resource LocalConnector
	err := ctx.ReadResource("dex:resources:LocalConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LocalConnector resources.
type localConnectorState struct {
}

type LocalConnectorState struct {
}

func (LocalConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*localConnectorState)(nil)).Elem()
}

type localConnectorArgs struct {
	// Unique identifier for the local connector.
	ConnectorId string `pulumi:"connectorId"`
	// Whether the local connector is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Human-readable name for the connector, displayed to users during login.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a LocalConnector resource.
type LocalConnectorArgs struct {
	// Unique identifier for the local connector.
	ConnectorId pulumi.StringInput
	// Whether the local connector is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Human-readable name for the connector, displayed to users during login.
	Name pulumi.StringInput
}

func (LocalConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*localConnectorArgs)(nil)).Elem()
}

type LocalConnectorInput interface {
	pulumi.Input

	ToLocalConnectorOutput() LocalConnectorOutput
	ToLocalConnectorOutputWithContext(ctx context.Context) LocalConnectorOutput
}

func (*LocalConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**LocalConnector)(nil)).Elem()
}

func (i *LocalConnector) ToLocalConnectorOutput() LocalConnectorOutput {
	return i.ToLocalConnectorOutputWithContext(context.Background())
}

func (i *LocalConnector) ToLocalConnectorOutputWithContext(ctx context.Context) LocalConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LocalConnectorOutput)
}

// LocalConnectorArrayInput is an input type that accepts LocalConnectorArray and LocalConnectorArrayOutput values.
// You can construct a concrete instance of `LocalConnectorArrayInput` via:
//
//	LocalConnectorArray{ LocalConnectorArgs{...} }
type LocalConnectorArrayInput interface {
	pulumi.Input

	ToLocalConnectorArrayOutput() LocalConnectorArrayOutput
	ToLocalConnectorArrayOutputWithContext(context.Context) LocalConnectorArrayOutput
}

type LocalConnectorArray []LocalConnectorInput

func (LocalConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LocalConnector)(nil)).Elem()
}

func (i LocalConnectorArray) ToLocalConnectorArrayOutput() LocalConnectorArrayOutput {
	return i.ToLocalConnectorArrayOutputWithContext(context.Background())
}

func (i LocalConnectorArray) ToLocalConnectorArrayOutputWithContext(ctx context.Context) LocalConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LocalConnectorArrayOutput)
}

// LocalConnectorMapInput is an input type that accepts LocalConnectorMap and LocalConnectorMapOutput values.
// You can construct a concrete instance of `LocalConnectorMapInput` via:
//
//	LocalConnectorMap{ "key": LocalConnectorArgs{...} }
type LocalConnectorMapInput interface {
	pulumi.Input

	ToLocalConnectorMapOutput() LocalConnectorMapOutput
	ToLocalConnectorMapOutputWithContext(context.Context) LocalConnectorMapOutput
}

type LocalConnectorMap map[string]LocalConnectorInput

func (LocalConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LocalConnector)(nil)).Elem()
}

func (i LocalConnectorMap) ToLocalConnectorMapOutput() LocalConnectorMapOutput {
	return i.ToLocalConnectorMapOutputWithContext(context.Background())
}

func (i LocalConnectorMap) ToLocalConnectorMapOutputWithContext(ctx context.Context) LocalConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LocalConnectorMapOutput)
}

type LocalConnectorOutput struct{ *pulumi.OutputState }

func (LocalConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LocalConnector)(nil)).Elem()
}

func (o LocalConnectorOutput) ToLocalConnectorOutput() LocalConnectorOutput {
	return o
}

func (o LocalConnectorOutput) ToLocalConnectorOutputWithContext(ctx context.Context) LocalConnectorOutput {
	return o
}

// Unique identifier for the local connector.
func (o LocalConnectorOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *LocalConnector) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// Whether the local connector is enabled. Defaults to true.
func (o LocalConnectorOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LocalConnector) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Human-readable name for the connector, displayed to users during login.
func (o LocalConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *LocalConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type LocalConnectorArrayOutput struct{ *pulumi.OutputState }

func (LocalConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LocalConnector)(nil)).Elem()
}

func (o LocalConnectorArrayOutput) ToLocalConnectorArrayOutput() LocalConnectorArrayOutput {
	return o
}

func (o LocalConnectorArrayOutput) ToLocalConnectorArrayOutputWithContext(ctx context.Context) LocalConnectorArrayOutput {
	return o
}

func (o LocalConnectorArrayOutput) Index(i pulumi.IntInput) LocalConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LocalConnector {
		return vs[0].([]*LocalConnector)[vs[1].(int)]
	}).(LocalConnectorOutput)
}

type LocalConnectorMapOutput struct{ *pulumi.OutputState }

func (LocalConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LocalConnector)(nil)).Elem()
}

func (o LocalConnectorMapOutput) ToLocalConnectorMapOutput() LocalConnectorMapOutput {
	return o
}

func (o LocalConnectorMapOutput) ToLocalConnectorMapOutputWithContext(ctx context.Context) LocalConnectorMapOutput {
	return o
}

func (o LocalConnectorMapOutput) MapIndex(k pulumi.StringInput) LocalConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LocalConnector {
		return vs[0].(map[string]*LocalConnector)[vs[1].(string)]
	}).(LocalConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LocalConnectorInput)(nil)).Elem(), &LocalConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*LocalConnectorArrayInput)(nil)).Elem(), LocalConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LocalConnectorMapInput)(nil)).Elem(), LocalConnectorMap{})
	pulumi.RegisterOutputType(LocalConnectorOutput{})
	pulumi.RegisterOutputType(LocalConnectorArrayOutput{})
	pulumi.RegisterOutputType(LocalConnectorMapOutput{})
}
