# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['AzureOidcConnectorArgs', 'AzureOidcConnector']

@pulumi.input_type
class AzureOidcConnectorArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 client_secret: pulumi.Input[_builtins.str],
                 connector_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 redirect_uri: pulumi.Input[_builtins.str],
                 tenant_id: pulumi.Input[_builtins.str],
                 extra_oidc: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 user_name_source: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a AzureOidcConnector resource.
        :param pulumi.Input[_builtins.str] client_id: Azure AD application (client) ID.
        :param pulumi.Input[_builtins.str] client_secret: Azure AD application client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the Azure connector.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
        :param pulumi.Input[_builtins.str] tenant_id: Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
        :param pulumi.Input[Mapping[str, Any]] extra_oidc: Additional OIDC configuration fields as key-value pairs for advanced scenarios.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] scopes: OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
        :param pulumi.Input[_builtins.str] user_name_source: Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "connector_id", connector_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        pulumi.set(__self__, "tenant_id", tenant_id)
        if extra_oidc is not None:
            pulumi.set(__self__, "extra_oidc", extra_oidc)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if user_name_source is not None:
            pulumi.set(__self__, "user_name_source", user_name_source)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        """
        Azure AD application (client) ID.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[_builtins.str]:
        """
        Azure AD application client secret.
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier for the Azure connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Input[_builtins.str]:
        """
        Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
        """
        return pulumi.get(self, "redirect_uri")

    @redirect_uri.setter
    def redirect_uri(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "redirect_uri", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Input[_builtins.str]:
        """
        Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
        """
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="extraOidc")
    def extra_oidc(self) -> Optional[pulumi.Input[Mapping[str, Any]]]:
        """
        Additional OIDC configuration fields as key-value pairs for advanced scenarios.
        """
        return pulumi.get(self, "extra_oidc")

    @extra_oidc.setter
    def extra_oidc(self, value: Optional[pulumi.Input[Mapping[str, Any]]]):
        pulumi.set(self, "extra_oidc", value)

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
        """
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "scopes", value)

    @_builtins.property
    @pulumi.getter(name="userNameSource")
    def user_name_source(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
        """
        return pulumi.get(self, "user_name_source")

    @user_name_source.setter
    def user_name_source(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_name_source", value)


@pulumi.type_token("dex:resources:AzureOidcConnector")
class AzureOidcConnector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_oidc: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 user_name_source: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages an Azure AD/Entra ID connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their Azure AD/Entra ID credentials.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_id: Azure AD application (client) ID.
        :param pulumi.Input[_builtins.str] client_secret: Azure AD application client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the Azure connector.
        :param pulumi.Input[Mapping[str, Any]] extra_oidc: Additional OIDC configuration fields as key-value pairs for advanced scenarios.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] scopes: OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
        :param pulumi.Input[_builtins.str] tenant_id: Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
        :param pulumi.Input[_builtins.str] user_name_source: Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AzureOidcConnectorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an Azure AD/Entra ID connector in Dex using the generic OIDC connector (type: oidc). This connector allows users to authenticate using their Azure AD/Entra ID credentials.

        :param str resource_name: The name of the resource.
        :param AzureOidcConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AzureOidcConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_oidc: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 user_name_source: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AzureOidcConnectorArgs.__new__(AzureOidcConnectorArgs)

            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            if client_secret is None and not opts.urn:
                raise TypeError("Missing required property 'client_secret'")
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            if connector_id is None and not opts.urn:
                raise TypeError("Missing required property 'connector_id'")
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["extra_oidc"] = extra_oidc
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if redirect_uri is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uri'")
            __props__.__dict__["redirect_uri"] = redirect_uri
            __props__.__dict__["scopes"] = scopes
            if tenant_id is None and not opts.urn:
                raise TypeError("Missing required property 'tenant_id'")
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["user_name_source"] = user_name_source
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(AzureOidcConnector, __self__).__init__(
            'dex:resources:AzureOidcConnector',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'AzureOidcConnector':
        """
        Get an existing AzureOidcConnector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = AzureOidcConnectorArgs.__new__(AzureOidcConnectorArgs)

        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_secret"] = None
        __props__.__dict__["connector_id"] = None
        __props__.__dict__["extra_oidc"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["redirect_uri"] = None
        __props__.__dict__["scopes"] = None
        __props__.__dict__["tenant_id"] = None
        __props__.__dict__["user_name_source"] = None
        return AzureOidcConnector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        Azure AD application (client) ID.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        Azure AD application client secret.
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier for the Azure connector.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="extraOidc")
    def extra_oidc(self) -> pulumi.Output[Optional[Mapping[str, Any]]]:
        """
        Additional OIDC configuration fields as key-value pairs for advanced scenarios.
        """
        return pulumi.get(self, "extra_oidc")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Output[_builtins.str]:
        """
        Redirect URI registered in Azure AD. Must match Dex's callback URL (typically 'https://dex.example.com/callback').
        """
        return pulumi.get(self, "redirect_uri")

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        OIDC scopes to request from Azure AD. Defaults to ['openid', 'profile', 'email', 'offline_access'] if not specified.
        """
        return pulumi.get(self, "scopes")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[_builtins.str]:
        """
        Azure AD tenant ID (UUID format). This identifies your Azure AD organization.
        """
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter(name="userNameSource")
    def user_name_source(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Source for the username claim. Valid values: 'preferred_username' (default), 'upn' (User Principal Name), or 'email'.
        """
        return pulumi.get(self, "user_name_source")

