# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ClientArgs', 'Client']

@pulumi.input_type
class ClientArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 redirect_uris: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 logo_url: Optional[pulumi.Input[_builtins.str]] = None,
                 public: Optional[pulumi.Input[_builtins.bool]] = None,
                 secret: Optional[pulumi.Input[_builtins.str]] = None,
                 trusted_peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Client resource.
        :param pulumi.Input[_builtins.str] client_id: Unique identifier for the OAuth2 client. This is used as the client_id in OAuth2 flows.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the OAuth2 client.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: List of allowed redirect URIs for OAuth2 authorization flows. Must be valid HTTP/HTTPS URLs.
        :param pulumi.Input[_builtins.str] logo_url: URL to a logo image for the OAuth2 client. Used in consent screens.
        :param pulumi.Input[_builtins.bool] public: If true, this client is a public client (e.g., mobile app) and does not require a client secret.
        :param pulumi.Input[_builtins.str] secret: Client secret for the OAuth2 client. If not provided, a secure random secret will be generated automatically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] trusted_peers: List of trusted peer client IDs that can exchange tokens with this client.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "redirect_uris", redirect_uris)
        if logo_url is not None:
            pulumi.set(__self__, "logo_url", logo_url)
        if public is not None:
            pulumi.set(__self__, "public", public)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if trusted_peers is not None:
            pulumi.set(__self__, "trusted_peers", trusted_peers)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier for the OAuth2 client. This is used as the client_id in OAuth2 flows.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable name for the OAuth2 client.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        List of allowed redirect URIs for OAuth2 authorization flows. Must be valid HTTP/HTTPS URLs.
        """
        return pulumi.get(self, "redirect_uris")

    @redirect_uris.setter
    def redirect_uris(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        URL to a logo image for the OAuth2 client. Used in consent screens.
        """
        return pulumi.get(self, "logo_url")

    @logo_url.setter
    def logo_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "logo_url", value)

    @_builtins.property
    @pulumi.getter
    def public(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, this client is a public client (e.g., mobile app) and does not require a client secret.
        """
        return pulumi.get(self, "public")

    @public.setter
    def public(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "public", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Client secret for the OAuth2 client. If not provided, a secure random secret will be generated automatically.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter(name="trustedPeers")
    def trusted_peers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of trusted peer client IDs that can exchange tokens with this client.
        """
        return pulumi.get(self, "trusted_peers")

    @trusted_peers.setter
    def trusted_peers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "trusted_peers", value)


@pulumi.type_token("dex:resources:Client")
class Client(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 logo_url: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 public: Optional[pulumi.Input[_builtins.bool]] = None,
                 redirect_uris: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 secret: Optional[pulumi.Input[_builtins.str]] = None,
                 trusted_peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Manages an OAuth2 client in Dex. OAuth2 clients are applications that can authenticate users through Dex.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_id: Unique identifier for the OAuth2 client. This is used as the client_id in OAuth2 flows.
        :param pulumi.Input[_builtins.str] logo_url: URL to a logo image for the OAuth2 client. Used in consent screens.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the OAuth2 client.
        :param pulumi.Input[_builtins.bool] public: If true, this client is a public client (e.g., mobile app) and does not require a client secret.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: List of allowed redirect URIs for OAuth2 authorization flows. Must be valid HTTP/HTTPS URLs.
        :param pulumi.Input[_builtins.str] secret: Client secret for the OAuth2 client. If not provided, a secure random secret will be generated automatically.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] trusted_peers: List of trusted peer client IDs that can exchange tokens with this client.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ClientArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an OAuth2 client in Dex. OAuth2 clients are applications that can authenticate users through Dex.

        :param str resource_name: The name of the resource.
        :param ClientArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ClientArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 logo_url: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 public: Optional[pulumi.Input[_builtins.bool]] = None,
                 redirect_uris: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 secret: Optional[pulumi.Input[_builtins.str]] = None,
                 trusted_peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ClientArgs.__new__(ClientArgs)

            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["logo_url"] = logo_url
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["public"] = public
            if redirect_uris is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uris'")
            __props__.__dict__["redirect_uris"] = redirect_uris
            __props__.__dict__["secret"] = None if secret is None else pulumi.Output.secret(secret)
            __props__.__dict__["trusted_peers"] = trusted_peers
            __props__.__dict__["created_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["secret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Client, __self__).__init__(
            'dex:resources:Client',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Client':
        """
        Get an existing Client resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ClientArgs.__new__(ClientArgs)

        __props__.__dict__["client_id"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["logo_url"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["public"] = None
        __props__.__dict__["redirect_uris"] = None
        __props__.__dict__["secret"] = None
        __props__.__dict__["trusted_peers"] = None
        return Client(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier for the OAuth2 client. This is used as the client_id in OAuth2 flows.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Timestamp when the client was created (RFC3339 format).
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        URL to a logo image for the OAuth2 client. Used in consent screens.
        """
        return pulumi.get(self, "logo_url")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable name for the OAuth2 client.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def public(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, this client is a public client (e.g., mobile app) and does not require a client secret.
        """
        return pulumi.get(self, "public")

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of allowed redirect URIs for OAuth2 authorization flows. Must be valid HTTP/HTTPS URLs.
        """
        return pulumi.get(self, "redirect_uris")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Client secret for the OAuth2 client. If not provided, a secure random secret will be generated automatically.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter(name="trustedPeers")
    def trusted_peers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of trusted peer client IDs that can exchange tokens with this client.
        """
        return pulumi.get(self, "trusted_peers")

