# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['GitHubConnectorArgs', 'GitHubConnector']

@pulumi.input_type
class GitHubConnectorArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 client_secret: pulumi.Input[_builtins.str],
                 connector_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 redirect_uri: pulumi.Input[_builtins.str],
                 host_name: Optional[pulumi.Input[_builtins.str]] = None,
                 load_all_groups: Optional[pulumi.Input[_builtins.bool]] = None,
                 orgs: Optional[pulumi.Input[Sequence[pulumi.Input['GitHubOrgArgs']]]] = None,
                 preferred_email_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 root_ca: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name_field: Optional[pulumi.Input[_builtins.str]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a GitHubConnector resource.
        :param pulumi.Input[_builtins.str] client_id: GitHub OAuth app client ID.
        :param pulumi.Input[_builtins.str] client_secret: GitHub OAuth app client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the GitHub connector.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[_builtins.str] host_name: GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
        :param pulumi.Input[_builtins.bool] load_all_groups: If true, load all groups (teams) the user is a member of. Defaults to false.
        :param pulumi.Input[Sequence[pulumi.Input['GitHubOrgArgs']]] orgs: List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
        :param pulumi.Input[_builtins.str] preferred_email_domain: Preferred email domain. If set, users with emails in this domain will be preferred.
        :param pulumi.Input[_builtins.str] root_ca: Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
        :param pulumi.Input[_builtins.str] team_name_field: Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
        :param pulumi.Input[_builtins.bool] use_login_as_id: If true, use GitHub login username as the user ID. Defaults to false.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "connector_id", connector_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        if host_name is not None:
            pulumi.set(__self__, "host_name", host_name)
        if load_all_groups is not None:
            pulumi.set(__self__, "load_all_groups", load_all_groups)
        if orgs is not None:
            pulumi.set(__self__, "orgs", orgs)
        if preferred_email_domain is not None:
            pulumi.set(__self__, "preferred_email_domain", preferred_email_domain)
        if root_ca is not None:
            pulumi.set(__self__, "root_ca", root_ca)
        if team_name_field is not None:
            pulumi.set(__self__, "team_name_field", team_name_field)
        if use_login_as_id is not None:
            pulumi.set(__self__, "use_login_as_id", use_login_as_id)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        """
        GitHub OAuth app client ID.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[_builtins.str]:
        """
        GitHub OAuth app client secret.
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier for the GitHub connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Input[_builtins.str]:
        """
        Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @redirect_uri.setter
    def redirect_uri(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "redirect_uri", value)

    @_builtins.property
    @pulumi.getter(name="hostName")
    def host_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
        """
        return pulumi.get(self, "host_name")

    @host_name.setter
    def host_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host_name", value)

    @_builtins.property
    @pulumi.getter(name="loadAllGroups")
    def load_all_groups(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, load all groups (teams) the user is a member of. Defaults to false.
        """
        return pulumi.get(self, "load_all_groups")

    @load_all_groups.setter
    def load_all_groups(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "load_all_groups", value)

    @_builtins.property
    @pulumi.getter
    def orgs(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GitHubOrgArgs']]]]:
        """
        List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
        """
        return pulumi.get(self, "orgs")

    @orgs.setter
    def orgs(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GitHubOrgArgs']]]]):
        pulumi.set(self, "orgs", value)

    @_builtins.property
    @pulumi.getter(name="preferredEmailDomain")
    def preferred_email_domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Preferred email domain. If set, users with emails in this domain will be preferred.
        """
        return pulumi.get(self, "preferred_email_domain")

    @preferred_email_domain.setter
    def preferred_email_domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "preferred_email_domain", value)

    @_builtins.property
    @pulumi.getter(name="rootCA")
    def root_ca(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
        """
        return pulumi.get(self, "root_ca")

    @root_ca.setter
    def root_ca(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "root_ca", value)

    @_builtins.property
    @pulumi.getter(name="teamNameField")
    def team_name_field(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
        """
        return pulumi.get(self, "team_name_field")

    @team_name_field.setter
    def team_name_field(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team_name_field", value)

    @_builtins.property
    @pulumi.getter(name="useLoginAsID")
    def use_login_as_id(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, use GitHub login username as the user ID. Defaults to false.
        """
        return pulumi.get(self, "use_login_as_id")

    @use_login_as_id.setter
    def use_login_as_id(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_login_as_id", value)


@pulumi.type_token("dex:resources:GitHubConnector")
class GitHubConnector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 host_name: Optional[pulumi.Input[_builtins.str]] = None,
                 load_all_groups: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 orgs: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GitHubOrgArgs', 'GitHubOrgArgsDict']]]]] = None,
                 preferred_email_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 root_ca: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name_field: Optional[pulumi.Input[_builtins.str]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Manages a GitHub connector in Dex. This connector allows users to authenticate using their GitHub accounts and supports organization and team-based access control.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_id: GitHub OAuth app client ID.
        :param pulumi.Input[_builtins.str] client_secret: GitHub OAuth app client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the GitHub connector.
        :param pulumi.Input[_builtins.str] host_name: GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
        :param pulumi.Input[_builtins.bool] load_all_groups: If true, load all groups (teams) the user is a member of. Defaults to false.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[Sequence[pulumi.Input[Union['GitHubOrgArgs', 'GitHubOrgArgsDict']]]] orgs: List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
        :param pulumi.Input[_builtins.str] preferred_email_domain: Preferred email domain. If set, users with emails in this domain will be preferred.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[_builtins.str] root_ca: Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
        :param pulumi.Input[_builtins.str] team_name_field: Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
        :param pulumi.Input[_builtins.bool] use_login_as_id: If true, use GitHub login username as the user ID. Defaults to false.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GitHubConnectorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a GitHub connector in Dex. This connector allows users to authenticate using their GitHub accounts and supports organization and team-based access control.

        :param str resource_name: The name of the resource.
        :param GitHubConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GitHubConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 host_name: Optional[pulumi.Input[_builtins.str]] = None,
                 load_all_groups: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 orgs: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GitHubOrgArgs', 'GitHubOrgArgsDict']]]]] = None,
                 preferred_email_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 root_ca: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name_field: Optional[pulumi.Input[_builtins.str]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GitHubConnectorArgs.__new__(GitHubConnectorArgs)

            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            if client_secret is None and not opts.urn:
                raise TypeError("Missing required property 'client_secret'")
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            if connector_id is None and not opts.urn:
                raise TypeError("Missing required property 'connector_id'")
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["host_name"] = host_name
            __props__.__dict__["load_all_groups"] = load_all_groups
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["orgs"] = orgs
            __props__.__dict__["preferred_email_domain"] = preferred_email_domain
            if redirect_uri is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uri'")
            __props__.__dict__["redirect_uri"] = redirect_uri
            __props__.__dict__["root_ca"] = root_ca
            __props__.__dict__["team_name_field"] = team_name_field
            __props__.__dict__["use_login_as_id"] = use_login_as_id
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(GitHubConnector, __self__).__init__(
            'dex:resources:GitHubConnector',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'GitHubConnector':
        """
        Get an existing GitHubConnector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = GitHubConnectorArgs.__new__(GitHubConnectorArgs)

        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_secret"] = None
        __props__.__dict__["connector_id"] = None
        __props__.__dict__["host_name"] = None
        __props__.__dict__["load_all_groups"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["orgs"] = None
        __props__.__dict__["preferred_email_domain"] = None
        __props__.__dict__["redirect_uri"] = None
        __props__.__dict__["root_ca"] = None
        __props__.__dict__["team_name_field"] = None
        __props__.__dict__["use_login_as_id"] = None
        return GitHubConnector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        GitHub OAuth app client ID.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        GitHub OAuth app client secret.
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier for the GitHub connector.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="hostName")
    def host_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        GitHub Enterprise hostname (e.g., 'github.example.com'). Leave empty for github.com.
        """
        return pulumi.get(self, "host_name")

    @_builtins.property
    @pulumi.getter(name="loadAllGroups")
    def load_all_groups(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, load all groups (teams) the user is a member of. Defaults to false.
        """
        return pulumi.get(self, "load_all_groups")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def orgs(self) -> pulumi.Output[Optional[Sequence['outputs.GitHubOrg']]]:
        """
        List of GitHub organizations with optional team restrictions. Only users in these orgs/teams will be allowed to authenticate.
        """
        return pulumi.get(self, "orgs")

    @_builtins.property
    @pulumi.getter(name="preferredEmailDomain")
    def preferred_email_domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Preferred email domain. If set, users with emails in this domain will be preferred.
        """
        return pulumi.get(self, "preferred_email_domain")

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Output[_builtins.str]:
        """
        Redirect URI registered in GitHub OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @_builtins.property
    @pulumi.getter(name="rootCA")
    def root_ca(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Root CA certificate for GitHub Enterprise (PEM format). Required if using self-signed certificates.
        """
        return pulumi.get(self, "root_ca")

    @_builtins.property
    @pulumi.getter(name="teamNameField")
    def team_name_field(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Field to use for team names in group claims. Valid values: 'name', 'slug', or 'both'. Defaults to 'slug'.
        """
        return pulumi.get(self, "team_name_field")

    @_builtins.property
    @pulumi.getter(name="useLoginAsID")
    def use_login_as_id(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, use GitHub login username as the user ID. Defaults to false.
        """
        return pulumi.get(self, "use_login_as_id")

