# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['GitLabConnectorArgs', 'GitLabConnector']

@pulumi.input_type
class GitLabConnectorArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 client_secret: pulumi.Input[_builtins.str],
                 connector_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 redirect_uri: pulumi.Input[_builtins.str],
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 get_groups_permission: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a GitLabConnector resource.
        :param pulumi.Input[_builtins.str] client_id: GitLab OAuth application client ID.
        :param pulumi.Input[_builtins.str] client_secret: GitLab OAuth application client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the GitLab connector.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[_builtins.str] base_url: GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
        :param pulumi.Input[_builtins.bool] get_groups_permission: If true, request 'read_api' scope to fetch group memberships. Defaults to false.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: List of GitLab group names. Only users in these groups will be allowed to authenticate.
        :param pulumi.Input[_builtins.bool] use_login_as_id: If true, use GitLab username as the user ID. Defaults to false.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "connector_id", connector_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        if base_url is not None:
            pulumi.set(__self__, "base_url", base_url)
        if get_groups_permission is not None:
            pulumi.set(__self__, "get_groups_permission", get_groups_permission)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if use_login_as_id is not None:
            pulumi.set(__self__, "use_login_as_id", use_login_as_id)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        """
        GitLab OAuth application client ID.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[_builtins.str]:
        """
        GitLab OAuth application client secret.
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier for the GitLab connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Input[_builtins.str]:
        """
        Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @redirect_uri.setter
    def redirect_uri(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "redirect_uri", value)

    @_builtins.property
    @pulumi.getter(name="baseURL")
    def base_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
        """
        return pulumi.get(self, "base_url")

    @base_url.setter
    def base_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "base_url", value)

    @_builtins.property
    @pulumi.getter(name="getGroupsPermission")
    def get_groups_permission(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, request 'read_api' scope to fetch group memberships. Defaults to false.
        """
        return pulumi.get(self, "get_groups_permission")

    @get_groups_permission.setter
    def get_groups_permission(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "get_groups_permission", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of GitLab group names. Only users in these groups will be allowed to authenticate.
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter(name="useLoginAsID")
    def use_login_as_id(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, use GitLab username as the user ID. Defaults to false.
        """
        return pulumi.get(self, "use_login_as_id")

    @use_login_as_id.setter
    def use_login_as_id(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_login_as_id", value)


@pulumi.type_token("dex:resources:GitLabConnector")
class GitLabConnector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 get_groups_permission: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Manages a GitLab connector in Dex. This connector allows users to authenticate using their GitLab accounts and supports group-based access control.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] base_url: GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
        :param pulumi.Input[_builtins.str] client_id: GitLab OAuth application client ID.
        :param pulumi.Input[_builtins.str] client_secret: GitLab OAuth application client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the GitLab connector.
        :param pulumi.Input[_builtins.bool] get_groups_permission: If true, request 'read_api' scope to fetch group memberships. Defaults to false.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: List of GitLab group names. Only users in these groups will be allowed to authenticate.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[_builtins.bool] use_login_as_id: If true, use GitLab username as the user ID. Defaults to false.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GitLabConnectorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a GitLab connector in Dex. This connector allows users to authenticate using their GitLab accounts and supports group-based access control.

        :param str resource_name: The name of the resource.
        :param GitLabConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GitLabConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 get_groups_permission: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 use_login_as_id: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GitLabConnectorArgs.__new__(GitLabConnectorArgs)

            __props__.__dict__["base_url"] = base_url
            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            if client_secret is None and not opts.urn:
                raise TypeError("Missing required property 'client_secret'")
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            if connector_id is None and not opts.urn:
                raise TypeError("Missing required property 'connector_id'")
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["get_groups_permission"] = get_groups_permission
            __props__.__dict__["groups"] = groups
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if redirect_uri is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uri'")
            __props__.__dict__["redirect_uri"] = redirect_uri
            __props__.__dict__["use_login_as_id"] = use_login_as_id
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(GitLabConnector, __self__).__init__(
            'dex:resources:GitLabConnector',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'GitLabConnector':
        """
        Get an existing GitLabConnector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = GitLabConnectorArgs.__new__(GitLabConnectorArgs)

        __props__.__dict__["base_url"] = None
        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_secret"] = None
        __props__.__dict__["connector_id"] = None
        __props__.__dict__["get_groups_permission"] = None
        __props__.__dict__["groups"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["redirect_uri"] = None
        __props__.__dict__["use_login_as_id"] = None
        return GitLabConnector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="baseURL")
    def base_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        GitLab instance base URL. Defaults to 'https://gitlab.com' for GitLab.com.
        """
        return pulumi.get(self, "base_url")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        GitLab OAuth application client ID.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        GitLab OAuth application client secret.
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier for the GitLab connector.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="getGroupsPermission")
    def get_groups_permission(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, request 'read_api' scope to fetch group memberships. Defaults to false.
        """
        return pulumi.get(self, "get_groups_permission")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of GitLab group names. Only users in these groups will be allowed to authenticate.
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Output[_builtins.str]:
        """
        Redirect URI registered in GitLab OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @_builtins.property
    @pulumi.getter(name="useLoginAsID")
    def use_login_as_id(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, use GitLab username as the user ID. Defaults to false.
        """
        return pulumi.get(self, "use_login_as_id")

