# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['GoogleConnectorArgs', 'GoogleConnector']

@pulumi.input_type
class GoogleConnectorArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 client_secret: pulumi.Input[_builtins.str],
                 connector_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 redirect_uri: pulumi.Input[_builtins.str],
                 domain_to_admin_email: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hosted_domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 prompt_type: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_file_path: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a GoogleConnector resource.
        :param pulumi.Input[_builtins.str] client_id: Google OAuth client ID.
        :param pulumi.Input[_builtins.str] client_secret: Google OAuth client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the Google connector.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] domain_to_admin_email: Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: List of Google Groups. Only users in these groups will be allowed to authenticate.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] hosted_domains: List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
        :param pulumi.Input[_builtins.str] prompt_type: OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
        :param pulumi.Input[_builtins.str] service_account_file_path: Path to Google service account JSON file. Required for group-based access control.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "connector_id", connector_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        if domain_to_admin_email is not None:
            pulumi.set(__self__, "domain_to_admin_email", domain_to_admin_email)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if hosted_domains is not None:
            pulumi.set(__self__, "hosted_domains", hosted_domains)
        if prompt_type is not None:
            pulumi.set(__self__, "prompt_type", prompt_type)
        if service_account_file_path is not None:
            pulumi.set(__self__, "service_account_file_path", service_account_file_path)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        """
        Google OAuth client ID.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[_builtins.str]:
        """
        Google OAuth client secret.
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique identifier for the Google connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Input[_builtins.str]:
        """
        Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @redirect_uri.setter
    def redirect_uri(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "redirect_uri", value)

    @_builtins.property
    @pulumi.getter(name="domainToAdminEmail")
    def domain_to_admin_email(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
        """
        return pulumi.get(self, "domain_to_admin_email")

    @domain_to_admin_email.setter
    def domain_to_admin_email(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domain_to_admin_email", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of Google Groups. Only users in these groups will be allowed to authenticate.
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter(name="hostedDomains")
    def hosted_domains(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
        """
        return pulumi.get(self, "hosted_domains")

    @hosted_domains.setter
    def hosted_domains(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "hosted_domains", value)

    @_builtins.property
    @pulumi.getter(name="promptType")
    def prompt_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
        """
        return pulumi.get(self, "prompt_type")

    @prompt_type.setter
    def prompt_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prompt_type", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountFilePath")
    def service_account_file_path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to Google service account JSON file. Required for group-based access control.
        """
        return pulumi.get(self, "service_account_file_path")

    @service_account_file_path.setter
    def service_account_file_path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_file_path", value)


@pulumi.type_token("dex:resources:GoogleConnector")
class GoogleConnector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_to_admin_email: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hosted_domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 prompt_type: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_file_path: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a Google connector in Dex. This connector allows users to authenticate using their Google accounts and supports domain and group-based access control.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_id: Google OAuth client ID.
        :param pulumi.Input[_builtins.str] client_secret: Google OAuth client secret.
        :param pulumi.Input[_builtins.str] connector_id: Unique identifier for the Google connector.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] domain_to_admin_email: Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] groups: List of Google Groups. Only users in these groups will be allowed to authenticate.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] hosted_domains: List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
        :param pulumi.Input[_builtins.str] name: Human-readable name for the connector, displayed to users during login.
        :param pulumi.Input[_builtins.str] prompt_type: OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
        :param pulumi.Input[_builtins.str] redirect_uri: Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
        :param pulumi.Input[_builtins.str] service_account_file_path: Path to Google service account JSON file. Required for group-based access control.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GoogleConnectorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Google connector in Dex. This connector allows users to authenticate using their Google accounts and supports domain and group-based access control.

        :param str resource_name: The name of the resource.
        :param GoogleConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GoogleConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_to_admin_email: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hosted_domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 prompt_type: Optional[pulumi.Input[_builtins.str]] = None,
                 redirect_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_file_path: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GoogleConnectorArgs.__new__(GoogleConnectorArgs)

            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            if client_secret is None and not opts.urn:
                raise TypeError("Missing required property 'client_secret'")
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            if connector_id is None and not opts.urn:
                raise TypeError("Missing required property 'connector_id'")
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["domain_to_admin_email"] = domain_to_admin_email
            __props__.__dict__["groups"] = groups
            __props__.__dict__["hosted_domains"] = hosted_domains
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["prompt_type"] = prompt_type
            if redirect_uri is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uri'")
            __props__.__dict__["redirect_uri"] = redirect_uri
            __props__.__dict__["service_account_file_path"] = service_account_file_path
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(GoogleConnector, __self__).__init__(
            'dex:resources:GoogleConnector',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'GoogleConnector':
        """
        Get an existing GoogleConnector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = GoogleConnectorArgs.__new__(GoogleConnectorArgs)

        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_secret"] = None
        __props__.__dict__["connector_id"] = None
        __props__.__dict__["domain_to_admin_email"] = None
        __props__.__dict__["groups"] = None
        __props__.__dict__["hosted_domains"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["prompt_type"] = None
        __props__.__dict__["redirect_uri"] = None
        __props__.__dict__["service_account_file_path"] = None
        return GoogleConnector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        Google OAuth client ID.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        Google OAuth client secret.
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique identifier for the Google connector.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="domainToAdminEmail")
    def domain_to_admin_email(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map of domain names to admin email addresses. Used for group lookups in Google Workspace.
        """
        return pulumi.get(self, "domain_to_admin_email")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of Google Groups. Only users in these groups will be allowed to authenticate.
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter(name="hostedDomains")
    def hosted_domains(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of Google Workspace domains. Only users with email addresses in these domains will be allowed to authenticate.
        """
        return pulumi.get(self, "hosted_domains")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable name for the connector, displayed to users during login.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="promptType")
    def prompt_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        OAuth prompt type. Valid values: 'consent' (default) or 'select_account'.
        """
        return pulumi.get(self, "prompt_type")

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Output[_builtins.str]:
        """
        Redirect URI registered in Google OAuth app. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @_builtins.property
    @pulumi.getter(name="serviceAccountFilePath")
    def service_account_file_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Path to Google service account JSON file. Required for group-based access control.
        """
        return pulumi.get(self, "service_account_file_path")

