# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GitHubOrg',
    'OIDCClaimMapping',
    'OIDCConfig',
]

@pulumi.output_type
class GitHubOrg(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 teams: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str name: GitHub organization name.
        :param Sequence[_builtins.str] teams: List of team names within the organization. If empty, all members of the organization can authenticate.
        """
        pulumi.set(__self__, "name", name)
        if teams is not None:
            pulumi.set(__self__, "teams", teams)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        GitHub organization name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def teams(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of team names within the organization. If empty, all members of the organization can authenticate.
        """
        return pulumi.get(self, "teams")


@pulumi.output_type
class OIDCClaimMapping(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "emailKey":
            suggest = "email_key"
        elif key == "groupsKey":
            suggest = "groups_key"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OIDCClaimMapping. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OIDCClaimMapping.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OIDCClaimMapping.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 email_key: Optional[_builtins.str] = None,
                 groups_key: Optional[_builtins.str] = None):
        """
        :param _builtins.str email_key: The OIDC claim key that contains the user's email address.
        :param _builtins.str groups_key: The OIDC claim key that contains the user's group memberships.
        """
        if email_key is not None:
            pulumi.set(__self__, "email_key", email_key)
        if groups_key is not None:
            pulumi.set(__self__, "groups_key", groups_key)

    @_builtins.property
    @pulumi.getter(name="emailKey")
    def email_key(self) -> Optional[_builtins.str]:
        """
        The OIDC claim key that contains the user's email address.
        """
        return pulumi.get(self, "email_key")

    @_builtins.property
    @pulumi.getter(name="groupsKey")
    def groups_key(self) -> Optional[_builtins.str]:
        """
        The OIDC claim key that contains the user's group memberships.
        """
        return pulumi.get(self, "groups_key")


@pulumi.output_type
class OIDCConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "clientId":
            suggest = "client_id"
        elif key == "clientSecret":
            suggest = "client_secret"
        elif key == "redirectUri":
            suggest = "redirect_uri"
        elif key == "claimMapping":
            suggest = "claim_mapping"
        elif key == "insecureIssuer":
            suggest = "insecure_issuer"
        elif key == "insecureSkipEmailVerified":
            suggest = "insecure_skip_email_verified"
        elif key == "userNameKey":
            suggest = "user_name_key"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OIDCConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OIDCConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OIDCConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 client_id: _builtins.str,
                 client_secret: _builtins.str,
                 issuer: _builtins.str,
                 redirect_uri: _builtins.str,
                 claim_mapping: Optional['outputs.OIDCClaimMapping'] = None,
                 extra: Optional[Mapping[str, Any]] = None,
                 insecure_issuer: Optional[_builtins.bool] = None,
                 insecure_skip_email_verified: Optional[_builtins.bool] = None,
                 scopes: Optional[Sequence[_builtins.str]] = None,
                 user_name_key: Optional[_builtins.str] = None):
        """
        :param _builtins.str client_id: The OIDC client ID.
        :param _builtins.str client_secret: The OIDC client secret.
        :param _builtins.str issuer: The OIDC issuer URL (e.g., 'https://accounts.google.com').
        :param _builtins.str redirect_uri: The redirect URI registered with the OIDC provider. Must match Dex's callback URL.
        :param 'OIDCClaimMapping' claim_mapping: Mapping of OIDC claims to Dex user attributes.
        :param Mapping[str, Any] extra: Additional OIDC configuration fields as key-value pairs.
        :param _builtins.bool insecure_issuer: If true, skip verification of the issuer URL. Not recommended for production.
        :param _builtins.bool insecure_skip_email_verified: If true, skip verification of the 'email_verified' claim. Not recommended for production.
        :param Sequence[_builtins.str] scopes: List of OIDC scopes to request (e.g., 'openid', 'profile', 'email'). Defaults to ['openid', 'profile', 'email'] if not specified.
        :param _builtins.str user_name_key: The claim key to use as the username (e.g., 'preferred_username', 'email', 'sub').
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "issuer", issuer)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        if claim_mapping is not None:
            pulumi.set(__self__, "claim_mapping", claim_mapping)
        if extra is not None:
            pulumi.set(__self__, "extra", extra)
        if insecure_issuer is not None:
            pulumi.set(__self__, "insecure_issuer", insecure_issuer)
        if insecure_skip_email_verified is not None:
            pulumi.set(__self__, "insecure_skip_email_verified", insecure_skip_email_verified)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if user_name_key is not None:
            pulumi.set(__self__, "user_name_key", user_name_key)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> _builtins.str:
        """
        The OIDC client ID.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> _builtins.str:
        """
        The OIDC client secret.
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> _builtins.str:
        """
        The OIDC issuer URL (e.g., 'https://accounts.google.com').
        """
        return pulumi.get(self, "issuer")

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> _builtins.str:
        """
        The redirect URI registered with the OIDC provider. Must match Dex's callback URL.
        """
        return pulumi.get(self, "redirect_uri")

    @_builtins.property
    @pulumi.getter(name="claimMapping")
    def claim_mapping(self) -> Optional['outputs.OIDCClaimMapping']:
        """
        Mapping of OIDC claims to Dex user attributes.
        """
        return pulumi.get(self, "claim_mapping")

    @_builtins.property
    @pulumi.getter
    def extra(self) -> Optional[Mapping[str, Any]]:
        """
        Additional OIDC configuration fields as key-value pairs.
        """
        return pulumi.get(self, "extra")

    @_builtins.property
    @pulumi.getter(name="insecureIssuer")
    def insecure_issuer(self) -> Optional[_builtins.bool]:
        """
        If true, skip verification of the issuer URL. Not recommended for production.
        """
        return pulumi.get(self, "insecure_issuer")

    @_builtins.property
    @pulumi.getter(name="insecureSkipEmailVerified")
    def insecure_skip_email_verified(self) -> Optional[_builtins.bool]:
        """
        If true, skip verification of the 'email_verified' claim. Not recommended for production.
        """
        return pulumi.get(self, "insecure_skip_email_verified")

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of OIDC scopes to request (e.g., 'openid', 'profile', 'email'). Defaults to ['openid', 'profile', 'email'] if not specified.
        """
        return pulumi.get(self, "scopes")

    @_builtins.property
    @pulumi.getter(name="userNameKey")
    def user_name_key(self) -> Optional[_builtins.str]:
        """
        The claim key to use as the username (e.g., 'preferred_username', 'email', 'sub').
        """
        return pulumi.get(self, "user_name_key")


