# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.1.0"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "dex Pulumi Package - Development Version"


setup(name='pulumi_kotaicode_dex',
      python_requires='>=3.9',
      version=VERSION,
      description="A Pulumi provider for managing Dex resources via the Dex gRPC Admin API",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='category/cloud',
      project_urls={
          'Repository': 'github.com/kotaicode/pulumi-provider-dex'
      },
      packages=find_packages(),
      package_data={
          'pulumi_kotaicode_dex': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.165.0,<4.0.0',
          'semver>=2.8.1',
          'typing-extensions>=4.11,<5; python_version < "3.11"'
      ],
      zip_safe=False)
