// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages an OAuth2 client in Dex.
 */
export class Client extends pulumi.CustomResource {
    /**
     * Get an existing Client resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Client {
        return new Client(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dex:index:Client';

    /**
     * Returns true if the given object is an instance of Client.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Client {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Client.__pulumiType;
    }

    declare public readonly clientId: pulumi.Output<string>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string | undefined>;
    declare public readonly logoUrl: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly public: pulumi.Output<boolean | undefined>;
    declare public readonly redirectUris: pulumi.Output<string[]>;
    declare public readonly secret: pulumi.Output<string | undefined>;
    declare public readonly trustedPeers: pulumi.Output<string[] | undefined>;

    /**
     * Create a Client resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClientArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.redirectUris === undefined && !opts.urn) {
                throw new Error("Missing required property 'redirectUris'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["logoUrl"] = args?.logoUrl;
            resourceInputs["name"] = args?.name;
            resourceInputs["public"] = args?.public;
            resourceInputs["redirectUris"] = args?.redirectUris;
            resourceInputs["secret"] = args?.secret ? pulumi.secret(args.secret) : undefined;
            resourceInputs["trustedPeers"] = args?.trustedPeers;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["logoUrl"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
            resourceInputs["redirectUris"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
            resourceInputs["trustedPeers"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Client.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Client resource.
 */
export interface ClientArgs {
    clientId: pulumi.Input<string>;
    logoUrl?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    public?: pulumi.Input<boolean>;
    redirectUris: pulumi.Input<pulumi.Input<string>[]>;
    secret?: pulumi.Input<string>;
    trustedPeers?: pulumi.Input<pulumi.Input<string>[]>;
}
