// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AzureMicrosoftConnectorArgs } from "./azureMicrosoftConnector";
export type AzureMicrosoftConnector = import("./azureMicrosoftConnector").AzureMicrosoftConnector;
export const AzureMicrosoftConnector: typeof import("./azureMicrosoftConnector").AzureMicrosoftConnector = null as any;
utilities.lazyLoad(exports, ["AzureMicrosoftConnector"], () => require("./azureMicrosoftConnector"));

export { AzureOidcConnectorArgs } from "./azureOidcConnector";
export type AzureOidcConnector = import("./azureOidcConnector").AzureOidcConnector;
export const AzureOidcConnector: typeof import("./azureOidcConnector").AzureOidcConnector = null as any;
utilities.lazyLoad(exports, ["AzureOidcConnector"], () => require("./azureOidcConnector"));

export { ClientArgs } from "./client";
export type Client = import("./client").Client;
export const Client: typeof import("./client").Client = null as any;
utilities.lazyLoad(exports, ["Client"], () => require("./client"));

export { CognitoOidcConnectorArgs } from "./cognitoOidcConnector";
export type CognitoOidcConnector = import("./cognitoOidcConnector").CognitoOidcConnector;
export const CognitoOidcConnector: typeof import("./cognitoOidcConnector").CognitoOidcConnector = null as any;
utilities.lazyLoad(exports, ["CognitoOidcConnector"], () => require("./cognitoOidcConnector"));

export { ConnectorArgs } from "./connector";
export type Connector = import("./connector").Connector;
export const Connector: typeof import("./connector").Connector = null as any;
utilities.lazyLoad(exports, ["Connector"], () => require("./connector"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "dex:index:AzureMicrosoftConnector":
                return new AzureMicrosoftConnector(name, <any>undefined, { urn })
            case "dex:index:AzureOidcConnector":
                return new AzureOidcConnector(name, <any>undefined, { urn })
            case "dex:index:Client":
                return new Client(name, <any>undefined, { urn })
            case "dex:index:CognitoOidcConnector":
                return new CognitoOidcConnector(name, <any>undefined, { urn })
            case "dex:index:Connector":
                return new Connector(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("dex", "index", _module)
pulumi.runtime.registerResourcePackage("dex", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:dex") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
