"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.outputs = exports.inputs = exports.LocalConnector = exports.GoogleConnector = exports.GitLabConnector = exports.GitHubConnector = exports.Connector = exports.CognitoOidcConnector = exports.Client = exports.AzureOidcConnector = exports.AzureMicrosoftConnector = exports.types = exports.resources = exports.config = exports.Provider = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
exports.Provider = null;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));
// Export sub-modules:
const config = require("./config");
exports.config = config;
const resources = require("./resources");
exports.resources = resources;
const types = require("./types");
exports.types = types;
// Re-export resources at top level for easier access.
// This allows:
//   import * as dex from "@kotaicode/pulumi-dex";
//   const c: dex.AzureOidcConnector = new dex.AzureOidcConnector(...);
//
// When isolatedModules is enabled, value and type exports must be separate.
var resources_1 = require("./resources");
Object.defineProperty(exports, "AzureMicrosoftConnector", { enumerable: true, get: function () { return resources_1.AzureMicrosoftConnector; } });
Object.defineProperty(exports, "AzureOidcConnector", { enumerable: true, get: function () { return resources_1.AzureOidcConnector; } });
Object.defineProperty(exports, "Client", { enumerable: true, get: function () { return resources_1.Client; } });
Object.defineProperty(exports, "CognitoOidcConnector", { enumerable: true, get: function () { return resources_1.CognitoOidcConnector; } });
Object.defineProperty(exports, "Connector", { enumerable: true, get: function () { return resources_1.Connector; } });
Object.defineProperty(exports, "GitHubConnector", { enumerable: true, get: function () { return resources_1.GitHubConnector; } });
Object.defineProperty(exports, "GitLabConnector", { enumerable: true, get: function () { return resources_1.GitLabConnector; } });
Object.defineProperty(exports, "GoogleConnector", { enumerable: true, get: function () { return resources_1.GoogleConnector; } });
Object.defineProperty(exports, "LocalConnector", { enumerable: true, get: function () { return resources_1.LocalConnector; } });
exports.inputs = require("./types/input");
exports.outputs = require("./types/output");
pulumi.runtime.registerResourcePackage("dex", {
    version: utilities.getVersion(),
    constructProvider: (name, type, urn) => {
        if (type !== "pulumi:providers:dex") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new exports.Provider(name, undefined, { urn });
    },
});
//# sourceMappingURL=index.js.map