// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";
import * as resources from "./resources";
import * as types from "./types";

export {
    config,
    resources,
    types,
};

// Re-export resources at top level for easier access
// This exports both the classes (values) and their types
export {
    AzureMicrosoftConnector,
    AzureMicrosoftConnectorArgs,
    AzureOidcConnector,
    AzureOidcConnectorArgs,
    Client,
    ClientArgs,
    CognitoOidcConnector,
    CognitoOidcConnectorArgs,
    Connector,
    ConnectorArgs,
    GitHubConnector,
    GitHubConnectorArgs,
    GitLabConnector,
    GitLabConnectorArgs,
    GoogleConnector,
    GoogleConnectorArgs,
    LocalConnector,
    LocalConnectorArgs,
} from "./resources";

// Re-export resource types explicitly for type annotations
// TypeScript classes can be used as types, but we also export them explicitly here
export type {
    AzureMicrosoftConnector,
    AzureOidcConnector,
    Client,
    CognitoOidcConnector,
    Connector,
    GitHubConnector,
    GitLabConnector,
    GoogleConnector,
    LocalConnector,
} from "./resources";

// Re-export input/output types for easier access
export * as inputs from "./types/input";
export * as outputs from "./types/output";

pulumi.runtime.registerResourcePackage("dex", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:dex") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
