// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'dex';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * PEM-encoded CA certificate for validating Dex's TLS certificate.
     */
    declare public readonly caCert: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded client certificate for mTLS to Dex.
     */
    declare public readonly clientCert: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded private key for the client certificate.
     */
    declare public readonly clientKey: pulumi.Output<string | undefined>;
    /**
     * Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
     */
    declare public readonly host: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            resourceInputs["caCert"] = args?.caCert ? pulumi.secret(args.caCert) : undefined;
            resourceInputs["clientCert"] = args?.clientCert ? pulumi.secret(args.clientCert) : undefined;
            resourceInputs["clientKey"] = args?.clientKey ? pulumi.secret(args.clientKey) : undefined;
            resourceInputs["host"] = args?.host;
            resourceInputs["insecureSkipVerify"] = pulumi.output(args?.insecureSkipVerify).apply(JSON.stringify);
            resourceInputs["timeoutSeconds"] = pulumi.output(args?.timeoutSeconds).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["caCert", "clientCert", "clientKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * PEM-encoded CA certificate for validating Dex's TLS certificate.
     */
    caCert?: pulumi.Input<string>;
    /**
     * PEM-encoded client certificate for mTLS to Dex.
     */
    clientCert?: pulumi.Input<string>;
    /**
     * PEM-encoded private key for the client certificate.
     */
    clientKey?: pulumi.Input<string>;
    /**
     * Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
     */
    host: pulumi.Input<string>;
    /**
     * If true, disables TLS verification (development only).
     */
    insecureSkipVerify?: pulumi.Input<boolean>;
    /**
     * Per-RPC timeout in seconds when talking to Dex.
     */
    timeoutSeconds?: pulumi.Input<number>;
}
