# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .azure_microsoft_connector import *
from .azure_oidc_connector import *
from .client import *
from .cognito_oidc_connector import *
from .connector import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_kotaicode_dex.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_kotaicode_dex.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "dex",
  "mod": "index",
  "fqn": "pulumi_kotaicode_dex",
  "classes": {
   "dex:index:AzureMicrosoftConnector": "AzureMicrosoftConnector",
   "dex:index:AzureOidcConnector": "AzureOidcConnector",
   "dex:index:Client": "Client",
   "dex:index:CognitoOidcConnector": "CognitoOidcConnector",
   "dex:index:Connector": "Connector"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "dex",
  "token": "pulumi:providers:dex",
  "fqn": "pulumi_kotaicode_dex",
  "class": "Provider"
 }
]
"""
)
