# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_kotaicode_dex.config as __config
    config = __config
    import pulumi_kotaicode_dex.resources as __resources
    resources = __resources
else:
    config = _utilities.lazy_import('pulumi_kotaicode_dex.config')
    resources = _utilities.lazy_import('pulumi_kotaicode_dex.resources')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "dex",
  "mod": "resources",
  "fqn": "pulumi_kotaicode_dex.resources",
  "classes": {
   "dex:resources:AzureMicrosoftConnector": "AzureMicrosoftConnector",
   "dex:resources:AzureOidcConnector": "AzureOidcConnector",
   "dex:resources:Client": "Client",
   "dex:resources:CognitoOidcConnector": "CognitoOidcConnector",
   "dex:resources:Connector": "Connector",
   "dex:resources:GitHubConnector": "GitHubConnector",
   "dex:resources:GitLabConnector": "GitLabConnector",
   "dex:resources:GoogleConnector": "GoogleConnector",
   "dex:resources:LocalConnector": "LocalConnector"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "dex",
  "token": "pulumi:providers:dex",
  "fqn": "pulumi_kotaicode_dex",
  "class": "Provider"
 }
]
"""
)
