# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'OIDCClaimMappingArgs',
    'OIDCClaimMappingArgsDict',
    'OIDCConfigArgs',
    'OIDCConfigArgsDict',
]

MYPY = False

if not MYPY:
    class OIDCClaimMappingArgsDict(TypedDict):
        email_key: NotRequired[pulumi.Input[_builtins.str]]
        groups_key: NotRequired[pulumi.Input[_builtins.str]]
elif False:
    OIDCClaimMappingArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class OIDCClaimMappingArgs:
    def __init__(__self__, *,
                 email_key: Optional[pulumi.Input[_builtins.str]] = None,
                 groups_key: Optional[pulumi.Input[_builtins.str]] = None):
        if email_key is not None:
            pulumi.set(__self__, "email_key", email_key)
        if groups_key is not None:
            pulumi.set(__self__, "groups_key", groups_key)

    @_builtins.property
    @pulumi.getter(name="emailKey")
    def email_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "email_key")

    @email_key.setter
    def email_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "email_key", value)

    @_builtins.property
    @pulumi.getter(name="groupsKey")
    def groups_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "groups_key")

    @groups_key.setter
    def groups_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "groups_key", value)


if not MYPY:
    class OIDCConfigArgsDict(TypedDict):
        client_id: pulumi.Input[_builtins.str]
        client_secret: pulumi.Input[_builtins.str]
        issuer: pulumi.Input[_builtins.str]
        redirect_uri: pulumi.Input[_builtins.str]
        claim_mapping: NotRequired[pulumi.Input['OIDCClaimMappingArgsDict']]
        extra: NotRequired[pulumi.Input[Mapping[str, Any]]]
        insecure_issuer: NotRequired[pulumi.Input[_builtins.bool]]
        insecure_skip_email_verified: NotRequired[pulumi.Input[_builtins.bool]]
        scopes: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
        user_name_key: NotRequired[pulumi.Input[_builtins.str]]
elif False:
    OIDCConfigArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class OIDCConfigArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[_builtins.str],
                 client_secret: pulumi.Input[_builtins.str],
                 issuer: pulumi.Input[_builtins.str],
                 redirect_uri: pulumi.Input[_builtins.str],
                 claim_mapping: Optional[pulumi.Input['OIDCClaimMappingArgs']] = None,
                 extra: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 insecure_issuer: Optional[pulumi.Input[_builtins.bool]] = None,
                 insecure_skip_email_verified: Optional[pulumi.Input[_builtins.bool]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 user_name_key: Optional[pulumi.Input[_builtins.str]] = None):
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "issuer", issuer)
        pulumi.set(__self__, "redirect_uri", redirect_uri)
        if claim_mapping is not None:
            pulumi.set(__self__, "claim_mapping", claim_mapping)
        if extra is not None:
            pulumi.set(__self__, "extra", extra)
        if insecure_issuer is not None:
            pulumi.set(__self__, "insecure_issuer", insecure_issuer)
        if insecure_skip_email_verified is not None:
            pulumi.set(__self__, "insecure_skip_email_verified", insecure_skip_email_verified)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if user_name_key is not None:
            pulumi.set(__self__, "user_name_key", user_name_key)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "issuer", value)

    @_builtins.property
    @pulumi.getter(name="redirectUri")
    def redirect_uri(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "redirect_uri")

    @redirect_uri.setter
    def redirect_uri(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "redirect_uri", value)

    @_builtins.property
    @pulumi.getter(name="claimMapping")
    def claim_mapping(self) -> Optional[pulumi.Input['OIDCClaimMappingArgs']]:
        return pulumi.get(self, "claim_mapping")

    @claim_mapping.setter
    def claim_mapping(self, value: Optional[pulumi.Input['OIDCClaimMappingArgs']]):
        pulumi.set(self, "claim_mapping", value)

    @_builtins.property
    @pulumi.getter
    def extra(self) -> Optional[pulumi.Input[Mapping[str, Any]]]:
        return pulumi.get(self, "extra")

    @extra.setter
    def extra(self, value: Optional[pulumi.Input[Mapping[str, Any]]]):
        pulumi.set(self, "extra", value)

    @_builtins.property
    @pulumi.getter(name="insecureIssuer")
    def insecure_issuer(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "insecure_issuer")

    @insecure_issuer.setter
    def insecure_issuer(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "insecure_issuer", value)

    @_builtins.property
    @pulumi.getter(name="insecureSkipEmailVerified")
    def insecure_skip_email_verified(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "insecure_skip_email_verified")

    @insecure_skip_email_verified.setter
    def insecure_skip_email_verified(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "insecure_skip_email_verified", value)

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "scopes", value)

    @_builtins.property
    @pulumi.getter(name="userNameKey")
    def user_name_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "user_name_key")

    @user_name_key.setter
    def user_name_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_name_key", value)


