// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("dex");

/**
 * PEM-encoded CA certificate for validating Dex's TLS certificate.
 */
export declare const caCert: string | undefined;
Object.defineProperty(exports, "caCert", {
    get() {
        return __config.get("caCert");
    },
    enumerable: true,
});

/**
 * PEM-encoded client certificate for mTLS to Dex.
 */
export declare const clientCert: string | undefined;
Object.defineProperty(exports, "clientCert", {
    get() {
        return __config.get("clientCert");
    },
    enumerable: true,
});

/**
 * PEM-encoded private key for the client certificate.
 */
export declare const clientKey: string | undefined;
Object.defineProperty(exports, "clientKey", {
    get() {
        return __config.get("clientKey");
    },
    enumerable: true,
});

/**
 * Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * If true, disables TLS verification (development only).
 */
export declare const insecureSkipVerify: boolean | undefined;
Object.defineProperty(exports, "insecureSkipVerify", {
    get() {
        return __config.getObject<boolean>("insecureSkipVerify");
    },
    enumerable: true,
});

/**
 * Per-RPC timeout in seconds when talking to Dex.
 */
export declare const timeoutSeconds: number | undefined;
Object.defineProperty(exports, "timeoutSeconds", {
    get() {
        return __config.getObject<number>("timeoutSeconds");
    },
    enumerable: true,
});

