"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
const pulumi = require("@pulumi/pulumi");
const __config = new pulumi.Config("dex");
Object.defineProperty(exports, "caCert", {
    get() {
        return __config.get("caCert");
    },
    enumerable: true,
});
Object.defineProperty(exports, "clientCert", {
    get() {
        return __config.get("clientCert");
    },
    enumerable: true,
});
Object.defineProperty(exports, "clientKey", {
    get() {
        return __config.get("clientKey");
    },
    enumerable: true,
});
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});
Object.defineProperty(exports, "insecureSkipVerify", {
    get() {
        return __config.getObject("insecureSkipVerify");
    },
    enumerable: true,
});
Object.defineProperty(exports, "timeoutSeconds", {
    get() {
        return __config.getObject("timeoutSeconds");
    },
    enumerable: true,
});
//# sourceMappingURL=vars.js.map