// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/kotaicode/pulumi-provider-dex/sdk/go/dex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// PEM-encoded CA certificate for validating Dex's TLS certificate.
func GetCaCert(ctx *pulumi.Context) string {
	return config.Get(ctx, "dex:caCert")
}

// PEM-encoded client certificate for mTLS to Dex.
func GetClientCert(ctx *pulumi.Context) string {
	return config.Get(ctx, "dex:clientCert")
}

// PEM-encoded private key for the client certificate.
func GetClientKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "dex:clientKey")
}

// Dex gRPC host:port, e.g. dex.internal.kotaicode:5557.
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "dex:host")
}

// If true, disables TLS verification (development only).
func GetInsecureSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "dex:insecureSkipVerify")
}

// Per-RPC timeout in seconds when talking to Dex.
func GetTimeoutSeconds(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "dex:timeoutSeconds")
}
